<?php
/**
 * Spanish fallbacks for visitor-facing template strings.
 *
 * WPML String Translation remains authoritative. These values are used only
 * when an earlier provider has left the English source text unchanged.
 *
 * @package Estecapelli
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/** Whether the current front-end request is Spanish. */
function estecapelli_is_spanish_request() {
	$language = (string) apply_filters( 'wpml_current_language', null );
	if ( function_exists( 'estecapelli_indexed_language_code' ) ) {
		return 'es' === estecapelli_indexed_language_code( $language );
	}
	if ( $language ) {
		return 'es' === $language;
	}

	return 0 === strpos( determine_locale(), 'es_' );
}

add_filter( 'gettext', 'estecapelli_es_gettext_fallback', 25, 3 );
/** Supply Spanish only when no earlier translation provider changed the text. */
function estecapelli_es_gettext_fallback( $translation, $text, $domain ) {
	if ( 'estecapelli' !== $domain || $translation !== $text || ! estecapelli_is_spanish_request() ) {
		return $translation;
	}

	static $strings = null;
	if ( null === $strings ) {
		$strings = array(
			// Shared navigation, footer and lead forms.
			'Skip to content' => 'Saltar al contenido',
			'Primary' => 'Navegación principal',
			'Toggle menu' => 'Abrir o cerrar el menú',
			'Choose language. Current language: %s' => 'Elige un idioma. Idioma actual: %s',
			'Free Consultation' => 'Consulta gratuita',
			'Book a consultation' => 'Reservar una consulta',
			'Ready to start your transformation?' => '¿Listo para comenzar tu transformación?',
			'Speak with our medical team — free, no obligation. Get a personalized plan based on your goals.' => 'Habla con nuestro equipo médico gratis y sin compromiso. Recibe un plan personalizado según tus objetivos.',
			'Get a Free Consultation' => 'Solicita una consulta gratuita',
			'Chat on WhatsApp' => 'Habla por WhatsApp',
			'Our Licences' => 'Nuestras acreditaciones',
			'Sitemap' => 'Mapa del sitio',
			'Language' => 'Idioma',
			'Get a free consultation — leave your details and we will reach out.' => 'Solicita una consulta gratuita: déjanos tus datos y nos pondremos en contacto contigo.',
			'Name and surname' => 'Nombre y apellidos',
			'Phone number' => 'Número de teléfono',
			'Request Call Back' => 'Solicitar una llamada',
			'All rights reserved.' => 'Todos los derechos reservados.',
			'Footer legal' => 'Enlaces legales del pie de página',
			'Privacy Policy' => 'Política de privacidad',
			'Terms' => 'Términos y condiciones',
			'Cookie Policy' => 'Política de cookies',
			'KVKK Notice' => 'Aviso KVKK',
			'Free Hair Analysis' => 'Análisis capilar gratuito',
			'Reply in 2 minutes' => 'Respuesta en 2 minutos',
			'Photo viewer' => 'Visor de imágenes',
			'Close' => 'Cerrar',
			'Previous photo' => 'Foto anterior',
			'Next photo' => 'Foto siguiente',
			'Book your free consultation' => 'Reserva tu consulta gratuita',
			'Leave your details and a medical consultant will get back to you shortly — no obligation.' => 'Déjanos tus datos y un asesor médico se pondrá en contacto contigo en breve, sin compromiso.',
			'Full name' => 'Nombre completo',
			'Phone' => 'Teléfono',
			'Email' => 'Correo electrónico',
			'Note' => 'Nota',
			'Tell us about your goals, or any questions you have…' => 'Cuéntanos tus objetivos o cualquier pregunta que tengas…',
			'Request a Free Consultation' => 'Solicitar una consulta gratuita',
			'Thank you! Your request has been received — our team will contact you shortly.' => '¡Gracias! Hemos recibido tu solicitud; nuestro equipo se pondrá en contacto contigo en breve.',
			'Hello Estecapelli, I would like to book a free consultation.' => 'Hola Estecapelli, me gustaría reservar una consulta gratuita.',

			// Blog landing and cards. Article content deliberately remains untouched.
			'From the Journal' => 'Desde nuestro blog',
			'Research, results & recovery' => 'Investigación, resultados y recuperación',
			'Expert articles on hair restoration, plastic surgery, dental treatment and the journey to your transformation — written by the Estecapelli team.' => 'Artículos especializados sobre restauración capilar, cirugía plástica, tratamientos dentales y el camino hacia tu transformación, escritos por el equipo de Estecapelli.',
			'Article categories' => 'Categorías de artículos',
			'All' => 'Todos',
			'Latest article' => 'Último artículo',
			'Read the article' => 'Leer el artículo',
			'Read more' => 'Leer más',
			'Posts pagination' => 'Paginación de artículos',
			'Newer' => 'Más recientes',
			'Older' => 'Más antiguos',
			'No articles have been published yet. New posts will appear here as soon as our team publishes them.' => 'Todavía no se ha publicado ningún artículo. Los nuevos contenidos aparecerán aquí en cuanto nuestro equipo los publique.',
			'Research, results and recovery — written by our team.' => 'Investigación, resultados y recuperación, explicados por nuestro equipo.',
			'View all articles' => 'Ver todos los artículos',
			'Write the first article' => 'Escribir el primer artículo',
			'No articles have been published yet. New posts will appear here as soon as your team publishes them.' => 'Todavía no se ha publicado ningún artículo. Los nuevos contenidos aparecerán aquí en cuanto tu equipo los publique.',

			// Contact page.
			'Hello Estecapelli, I would like a free analysis. Here are my photos:' => 'Hola Estecapelli, me gustaría recibir un análisis gratuito. Estas son mis fotos:',
			'English' => 'Inglés',
			'French' => 'Francés',
			'Italian' => 'Italiano',
			'Spanish' => 'Español',
			'Polish' => 'Polaco',
			'Portuguese' => 'Portugués',
			'Contact Us' => 'Contáctanos',
			'Let’s start your journey' => 'Comencemos tu proceso',
			'Reach our team by WhatsApp, phone or email — or leave your details and a medical consultant will get back to you in your own language.' => 'Contacta con nuestro equipo por WhatsApp, teléfono o correo electrónico, o déjanos tus datos y un asesor médico te responderá en tu idioma.',
			'We usually reply within an hour' => 'Normalmente respondemos en menos de una hora',
			'Chat with us now' => 'Habla con nosotros ahora',
			'Call' => 'Llamar',
			'Request a free consultation' => 'Solicita una consulta gratuita',
			'Tell us a little about you and we’ll be in touch shortly.' => 'Cuéntanos un poco sobre ti y nos pondremos en contacto contigo en breve.',
			'Interested in' => 'Tratamiento de interés',
			'Select a treatment' => 'Selecciona un tratamiento',
			'Hair Transplant' => 'Trasplante capilar',
			'Plastic Surgery' => 'Cirugía plástica',
			'Dental Treatment' => 'Tratamiento dental',
			'Not sure yet' => 'Todavía no estoy seguro',
			'Message' => 'Mensaje',
			'Send Request' => 'Enviar solicitud',
			'Please enter a valid phone number.' => 'Introduce un número de teléfono válido.',
			'Please enter a valid email address.' => 'Introduce una dirección de correo electrónico válida.',
			'Please enter your name.' => 'Introduce tu nombre.',
			'Name is required.' => 'El nombre es obligatorio.',
			'Visit & reach us' => 'Visítanos o contáctanos',
			'Address' => 'Dirección',
			'Working hours' => 'Horario de atención',
			'Monday – Sunday: 09:00 – 18:00 (GMT+3)' => 'Lunes – domingo: 09:00 – 18:00 (GMT+3)',
			'What happens next?' => '¿Qué ocurre después?',
			'We review your request and reach out to understand your goals.' => 'Revisamos tu solicitud y te contactamos para conocer tus objetivos.',
			'You receive a free, personalised treatment plan and quote.' => 'Recibes gratuitamente un plan de tratamiento y un presupuesto personalizados.',
			'We arrange your dates, travel and stay — and welcome you to Istanbul.' => 'Organizamos tus fechas, el viaje y la estancia, y te damos la bienvenida en Estambul.',
			'Send your photos, get a free analysis' => 'Envía tus fotos y recibe un análisis gratuito',
			'Share a few photos of your hair, face or smile and our specialists will assess your case and recommend the right approach — at no cost and with no obligation.' => 'Comparte algunas fotos de tu cabello, rostro o sonrisa y nuestros especialistas evaluarán tu caso y recomendarán el enfoque adecuado, gratis y sin compromiso.',
			'Send Photos on WhatsApp' => 'Enviar fotos por WhatsApp',
			'Talk to us in your own language' => 'Habla con nosotros en tu idioma',
			'Estecapelli clinic location' => 'Ubicación de la clínica Estecapelli',

			// Before/After, doctors and reusable controls.
			'Before' => 'Antes',
			'After' => 'Después',
			'Before & After' => 'Antes y después',
			'Before treatment' => 'Antes del tratamiento',
			'After treatment' => 'Después del tratamiento',
			'%s grafts' => '%s injertos',
			'Before and after results' => 'Resultados antes y después',
			'Real Results' => 'Resultados reales',
			'Before &amp; After' => 'Antes y después',
			'Outcomes from our %s patients.' => 'Resultados de nuestros pacientes de %s.',
			'Previous result' => 'Resultado anterior',
			'Next result' => 'Resultado siguiente',
			'Results will appear here soon.' => 'Los resultados aparecerán aquí próximamente.',
			'Treatment categories' => 'Categorías de tratamientos',
			'%s services' => 'Servicios de %s',
			'View treatment' => 'Ver tratamiento',
			'Enlarge result' => 'Ampliar resultado',
			'Before and after result' => 'Resultado antes y después',
			'grafts' => 'injertos',
			'See full gallery' => 'Ver la galería completa',
			'Résumé' => 'Currículum',
			'Book a Free Consultation' => 'Reservar una consulta gratuita',
			'View Résumé' => 'Ver currículum',
			'Meet the doctor' => 'Conoce al doctor',
			'Languages spoken' => 'Idiomas',
			'Procedure quick facts' => 'Datos rápidos del procedimiento',
			'Get Started' => 'Comenzar',
			'Learn More' => 'Más información',
			'Learn more' => 'Más información',

			// Homepage hero and service discovery.
			'Highlights' => 'Destacados',
			'Signature Methods' => 'Métodos exclusivos',
			'Select a method to play' => 'Selecciona un método para reproducirlo',
			'World-Class Experience' => 'Experiencia de nivel mundial',
			'Estecapelli patient result' => 'Resultado de un paciente de Estecapelli',
			'Previous patient' => 'Paciente anterior',
			'Next patient' => 'Paciente siguiente',
			'Estecapelli Dental' => 'Estecapelli Dental',
			'Estecapelli dental patient smiling' => 'Paciente de Estecapelli Dental sonriendo',
			'A Smile Designed Around You' => 'Una sonrisa diseñada para ti',
			'Hollywood smiles, veneers and full-mouth restorations — crafted by our specialists for a natural, confident result that lasts.' => 'Hollywood Smile, carillas y rehabilitaciones completas creadas por nuestros especialistas para conseguir un resultado natural, seguro y duradero.',
			'Hollywood Smile & porcelain veneers' => 'Hollywood Smile y carillas de porcelana',
			'Implants & full-mouth restoration' => 'Implantes y rehabilitación bucal completa',
			'One trusted clinic, all-inclusive care' => 'Una clínica de confianza con atención integral',
			'Explore Dental Treatments' => 'Descubre los tratamientos dentales',
			'Previous slide' => 'Diapositiva anterior',
			'Next slide' => 'Diapositiva siguiente',
			'Choose slide' => 'Elegir diapositiva',
			'Slide %d' => 'Diapositiva %d',
			'OUR SIGNATURE METHODS' => 'NUESTROS MÉTODOS EXCLUSIVOS',
			'Two techniques. Registered to our name.' => 'Dos técnicas registradas a nuestro nombre.',
			'Two exclusive, trademarked protocols — developed in-house.' => 'Dos protocolos exclusivos y registrados, desarrollados por nuestro equipo.',
			'Treatment' => 'Tratamiento',
			'Explore VITA®' => 'Descubre VITA®',
			'Explore Exosome®' => 'Descubre Exosome®',
			'EST. 2010 · ISTANBUL' => 'DESDE 2010 · ESTAMBUL',
			'EST. 2010 · ISTANBUL, TÜRKİYE' => 'DESDE 2010 · ESTAMBUL, TURQUÍA',
			'One of the World’s Most Experienced Hair Restoration Teams' => 'Uno de los equipos de restauración capilar con más experiencia del mundo',
			'Join the thousands who have come to Estecapelli to regain their confidence.' => 'Únete a los miles de pacientes que han elegido Estecapelli para recuperar su confianza.',
			'Schedule a Free Consultation' => 'Reserva una consulta gratuita',
			'Over 50,000+' => 'Más de 50.000',
			'5-Star Results' => 'Resultados de 5 estrellas',
			'Actual Estecapelli patient. Individual results may vary.' => 'Paciente real de Estecapelli. Los resultados individuales pueden variar.',
			'FIFTEEN YEARS' => 'QUINCE AÑOS',
			'FOR WOMEN · DISCREET & NATURAL' => 'PARA MUJERES · DISCRETO Y NATURAL',
			'Women’s Hair Transplant in Istanbul' => 'Trasplante capilar para mujeres en Estambul',
			'Thinning along the parting, a receding hairline or overall loss of density affects women too. Our female-focused approach restores fullness with unshaven techniques, complete privacy and natural, permanent results.' => 'La pérdida de densidad en la raya, el retroceso de la línea frontal o el afinamiento general también afectan a las mujeres. Nuestro enfoque especializado recupera el volumen con técnicas sin rasurado, total privacidad y resultados naturales y permanentes.',
			'Unshaven, discreet techniques' => 'Técnicas discretas sin rasurado',
			'Natural hairline & density design' => 'Diseño natural de línea frontal y densidad',
			'Female patient privacy at every step' => 'Privacidad para la paciente en cada etapa',
			'Years of Experience' => 'Años de experiencia',
			'Happy Patients' => 'Pacientes satisfechos',
			'Countries Served' => 'Países atendidos',
			'Support Team' => 'Equipo de atención',
			'What We Treat' => 'Qué tratamos',
			'Pick a field. See our signature treatments.' => 'Elige un área y descubre nuestros tratamientos más destacados.',
			'Switch between tabs to explore the methods we are best known for in each field of care.' => 'Cambia de pestaña para descubrir los métodos por los que somos más reconocidos en cada área de atención.',
			'Previous treatments' => 'Tratamientos anteriores',
			'Next treatments' => 'Tratamientos siguientes',

			// Homepage supporting sections.
			'The Comparison' => 'La comparación',
			'Global standards, Turkish expertise.' => 'Estándares internacionales, experiencia turca.',
			'See how our comprehensive approach and advanced techniques set us apart from other clinics.' => 'Descubre cómo nuestro enfoque integral y nuestras técnicas avanzadas nos diferencian de otras clínicas.',
			'Built for patients who refuse to compromise.' => 'Pensado para pacientes que no aceptan concesiones.',
			'At Estecapelli, we go beyond expectations to deliver personalised, high-quality care backed by years of experience and international standards. Our expert team combines innovative methods with a patient-first approach to deliver results that look natural and feel confident.' => 'En Estecapelli superamos las expectativas con una atención personalizada y de alta calidad, respaldada por años de experiencia y estándares internacionales. Nuestro equipo combina métodos innovadores con un enfoque centrado en el paciente para lograr resultados naturales que devuelven la confianza.',
			'Experience the Estecapelli difference — advanced techniques, patient-focused care.' => 'Descubre la diferencia Estecapelli: técnicas avanzadas y atención centrada en el paciente.',
			'Other Clinics' => 'Otras clínicas',
			'Premium Care' => 'Atención premium',
			'Standard Care' => 'Atención estándar',
			'5-Star Hotel Accommodation' => 'Alojamiento en hotel de 5 estrellas',
			'VIP Transfer Service' => 'Servicio de traslado VIP',
			'Personal Translator' => 'Intérprete personal',
			'Latest Technology Implementation' => 'Tecnología de última generación',
			'Success-Oriented Treatment Planning' => 'Planificación orientada al resultado',
			'Innovative Techniques (Exosome, FUE, DHI, VITA)' => 'Técnicas innovadoras (Exosome, FUE, DHI, VITA)',
			'Regenerative Stem Cell Therapy' => 'Terapia regenerativa con células madre',
			'Dedicated Post-Op Follow-Up Team' => 'Equipo especializado en seguimiento posoperatorio',
			'Pain-Free Anaesthesia' => 'Anestesia sin dolor',
			'Nine details where every choice matters.' => 'Nueve detalles en los que cada elección importa.',
			'Our Expertise' => 'Nuestra experiencia',
			'Three methods that shape every treatment.' => 'Tres métodos que dan forma a cada tratamiento.',
			'Two are exclusively ours. One sets the standard for personalised planning. All three power the results our patients trust us for.' => 'Dos son exclusivamente nuestros y uno establece el estándar de la planificación personalizada. Los tres impulsan los resultados por los que confían en nosotros nuestros pacientes.',
			'Patented · Estecapelli Exclusive' => 'Patentado · Exclusivo de Estecapelli',
			'Premium Hair Transplant Method' => 'Método premium de trasplante capilar',
			'Mesenchymal stem-cell support that keeps follicles alive longer.' => 'Apoyo con células madre mesenquimales para mantener los folículos vivos durante más tiempo.',
			'Follicle survival over 72 hours' => 'Supervivencia folicular durante más de 72 horas',
			'Learn about Exosome FUE' => 'Descubre Exosome FUE',
			'AI-Powered Diagnosis' => 'Diagnóstico asistido por IA',
			'Millimetric Hair & Scalp Analysis' => 'Análisis milimétrico del cabello y el cuero cabelludo',
			'AI maps your scalp before a single graft is planned.' => 'La IA analiza tu cuero cabelludo antes de planificar un solo injerto.',
			'Millimetric' => 'Milimétrica',
			'Precision per scalp scan' => 'Precisión en cada exploración del cuero cabelludo',
			'Learn more about TrichoLab' => 'Más información sobre TrichoLab',
			'Signature Protocol · Estecapelli Exclusive' => 'Protocolo exclusivo · Exclusivo de Estecapelli',
			'Power Derived from Vitamins' => 'El poder de las vitaminas',
			'A vitamin-cooled bath that keeps grafts strong out of the body.' => 'Una solución vitamínica refrigerada que mantiene fuertes los injertos fuera del cuerpo.',
			'Cool-Vapor' => 'Vapor frío',
			'Vitamin-nourished grafts' => 'Injertos nutridos con vitaminas',
			'Learn more about VITA' => 'Más información sobre VITA',
			'Real Stories' => 'Historias reales',
			'Their results speak louder than any ad ever could.' => 'Sus resultados dicen más que cualquier anuncio.',
			'Hear, in their own words, how patients from around the world describe their Estecapelli journey — from first consultation to long-term result.' => 'Escucha cómo pacientes de todo el mundo describen con sus propias palabras su experiencia en Estecapelli, desde la primera consulta hasta el resultado a largo plazo.',
			'Grafts' => 'Injertos',
			'Technique' => 'Técnica',
			'Patient from' => 'Paciente de',
			'More patient stories' => 'Más historias de pacientes',
			'On the playlist' => 'En la lista de reproducción',
			'Our Clinic' => 'Nuestra clínica',
			'Step inside our Istanbul clinic' => 'Conoce nuestra clínica de Estambul',
			'A Ministry-of-Health licensed, hospital-grade facility in the heart of Istanbul — modern operation rooms, sterile theatres and a permanent on-site medical team.' => 'Una instalación de nivel hospitalario autorizada por el Ministerio de Salud en el corazón de Estambul, con quirófanos modernos, áreas estériles y un equipo médico permanente en la clínica.',
			'Clinic walkthrough' => 'Recorrido por la clínica',
			'Hair Transplant Surgery Room' => 'Sala de trasplante capilar',
			'TrichoLab Room' => 'Sala TrichoLab',
			'Lobby' => 'Recepción',
			'Dental Clinic' => 'Clínica dental',
			'Our partner hotels' => 'Nuestros hoteles asociados',
			'Hair Analysis Lab' => 'Laboratorio de análisis capilar',
			'Your Personalised Hair Plan, Powered by Estecapelli' => 'Tu plan capilar personalizado, desarrollado por Estecapelli',
			'I know my hair-loss area' => 'Conozco la zona donde pierdo cabello',
			'Start self-assessment' => 'Iniciar autoevaluación',
			'Analyse my photos with AI' => 'Analizar mis fotos con IA',
			'Start AI Analysis' => 'Iniciar análisis con IA',
			'Back to options' => 'Volver a las opciones',
			'Tap the areas where you are losing hair' => 'Toca las zonas donde estás perdiendo cabello',
			'Selected areas' => 'Zonas seleccionadas',
			'No area selected yet.' => 'Todavía no has seleccionado ninguna zona.',
			'Your name' => 'Tu nombre',
			'Phone / WhatsApp' => 'Teléfono / WhatsApp',
			'Your number' => 'Tu número',
			'Your email' => 'Tu correo electrónico',
			'Get my analysis' => 'Recibir mi análisis',
			'Real Patients · Real Results' => 'Pacientes reales · Resultados reales',
			'Choose a hair-transplant technique to browse real patient results.' => 'Elige una técnica de trasplante capilar para ver resultados de pacientes reales.',
			'Hair transplant techniques' => 'Técnicas de trasplante capilar',
			'View all results' => 'Ver todos los resultados',

			// Shared controls, accessibility and utility labels.
			'%1$s grafts · %2$s' => '%1$s injertos · %2$s',
			'Close video' => 'Cerrar vídeo',
			'Back to gallery' => 'Volver a la galería',
			'Click any photo to open the gallery' => 'Haz clic en cualquier foto para abrir la galería',
			'Contents' => 'Contenido',
			'Enlarge photo' => 'Ampliar foto',
			'Go to photo %d' => 'Ir a la foto %d',
			'Hover or tap to discover' => 'Pasa el cursor o toca para descubrir',
			'Included' => 'Incluido',
			'Included at Estecapelli' => 'Incluido en Estecapelli',
			'Not included' => 'No incluido',
			'Next step' => 'Paso siguiente',
			'Previous step' => 'Paso anterior',
			'Open gallery: %s' => 'Abrir galería: %s',
			'Open the gallery' => 'Abrir la galería',
			'Play %s video' => 'Reproducir vídeo de %s',
			'Play %s — %s' => 'Reproducir %s — %s',
			'Procedure details' => 'Detalles del procedimiento',
			'Rated %d out of 5' => 'Valoración: %d de 5',
			'Scalp zones' => 'Zonas del cuero cabelludo',
			'Scroll left' => 'Desplazar a la izquierda',
			'Scroll right' => 'Desplazar a la derecha',
			'Steps' => 'Pasos',
			'Treatments' => 'Tratamientos',
			'Trustpilot rating: 5 out of 5, Excellent' => 'Valoración en Trustpilot: 5 de 5, Excelente',
			'Use the arrows to browse · click any photo to enlarge' => 'Usa las flechas para navegar · haz clic en una foto para ampliarla',
			'View result %d' => 'Ver resultado %d',
			'step' => 'paso',
			'Excellent' => 'Excelente',
			'on Trustpilot' => 'en Trustpilot',
			'Google Reviews' => 'Reseñas de Google',
			'Estecapelli in numbers' => 'Estecapelli en cifras',
			'Patients trust us by the numbers' => 'La confianza de nuestros pacientes en cifras',
			'Estecapelli versus other clinics — feature comparison' => 'Estecapelli frente a otras clínicas — comparación de servicios',
			'Internationally Accredited & Certified' => 'Acreditación y certificación internacionales',
			'Internationally accredited & certified — Ministry of Health, Certified Medical Travel Agency, HRSA, NACo Award, ISO 13485' => 'Acreditación y certificación internacionales — Ministerio de Salud, agencia certificada de turismo médico, HRSA, premio NACo e ISO 13485',
			'Internationally accredited — Ministry of Health, HRSA, NACo, ISO 13485, Certified Medical Travel Agency' => 'Acreditación internacional — Ministerio de Salud, HRSA, NACo, ISO 13485 y agencia certificada de turismo médico',
			'Internationally accredited — Ministry of Health, HRSA, NACo, ISO 13485, Certified Medical Travel Agent' => 'Acreditación internacional — Ministerio de Salud, HRSA, NACo, ISO 13485 y agente certificado de turismo médico',

			// About flyout and treatment cards.
			'Aesthetic Excellence, Backed by Medical Trust.' => 'Excelencia estética respaldada por la confianza médica.',
			"From hair restoration to plastic, dental and non-surgical aesthetics — Estecapelli's board-certified doctors deliver hospital-grade care with the precision your transformation deserves." => 'Desde la restauración capilar hasta la cirugía plástica, la odontología y la medicina estética no quirúrgica, los médicos cualificados de Estecapelli ofrecen atención de nivel hospitalario con la precisión que merece tu transformación.',
			'Dr. Mehmet Hanifi Kutlar' => 'Dr. Mehmet Hanifi Kutlar',
			'Medical Director & Co-founder' => 'Director médico y cofundador',
			'15+ years in aesthetic medicine' => 'Más de 15 años en medicina estética',
			'ACCREDITED CLINIC' => 'CLÍNICA ACREDITADA',
			'Ministry of Health Licensed' => 'Autorizada por el Ministerio de Salud',
			'ISO 9001 · TURSAB Certified' => 'Certificada por ISO 9001 · TURSAB',
			'About Estecapelli' => 'Sobre Estecapelli',
			'About Us' => 'Sobre nosotros',
			'Who we are and what drives our clinic forward.' => 'Quiénes somos y qué impulsa nuestra clínica.',
			'Our Doctors' => 'Nuestros doctores',
			'Meet the surgeons leading every procedure.' => 'Conoce a los cirujanos que dirigen cada intervención.',
			'Our Team' => 'Nuestro equipo',
			'The full medical and patient-care team behind your treatment.' => 'Todo el equipo médico y de atención al paciente que está detrás de tu tratamiento.',
			'Visit Us' => 'Visítanos',
			'Medical Treatment' => 'Tratamiento médico',
			'Hair Transplant Care & Technology' => 'Cuidados y tecnología del trasplante capilar',
			'Micro Sapphire FUE' => 'Micro Sapphire FUE',
			'Sapphire FUE Hair Transplant' => 'Trasplante capilar FUE Zafiro',
			'Sapphire-blade precision for natural density and faster healing.' => 'Precisión con cuchillas de zafiro para una densidad natural y una recuperación más rápida.',
			'A natural and permanent hair transplant technique where follicles are placed via sapphire blades.' => 'Una técnica de trasplante capilar natural y permanente en la que los folículos se implantan mediante cuchillas de zafiro.',
			'DHI Hair Transplant' => 'Trasplante capilar DHI',
			'A modern hair transplantation method performed with a Choi pen that allows precise placement.' => 'Un método moderno de trasplante capilar realizado con un lápiz Choi que permite una implantación precisa.',
			'Choi-pen implantation for precise angle and direction control.' => 'Implantación con lápiz Choi para controlar con precisión el ángulo y la dirección.',
			'Exosome FUE Hair Transplant' => 'Trasplante capilar Exosome FUE',
			'Exosome Treatment' => 'Tratamiento Exosome',
			'Cell-regenerating exosomes that keep follicles alive longer.' => 'Exosomas regeneradores que mantienen los folículos vivos durante más tiempo.',
			'Supported by cell-regenerating exosomes, it keeps hair follicles alive for longer-lasting density.' => 'Con el apoyo de exosomas regeneradores, mantiene vivos los folículos para conseguir una densidad más duradera.',
			'VITA Treatment' => 'Tratamiento VITA',
			"Estecapelli's signature protocol that revitalises scalp & strands." => 'El protocolo exclusivo de Estecapelli que revitaliza el cuero cabelludo y el cabello.',
			"Estecapelli's signature method that revitalizes the scalp and strengthens hair." => 'El método exclusivo de Estecapelli que revitaliza el cuero cabelludo y fortalece el cabello.',
			'POPULAR' => 'POPULAR',
			'SIGNATURE' => 'EXCLUSIVO',
			'Rhinoplasty' => 'Rinoplastia',
			'Nose reshaping that refines proportions and function.' => 'Remodelación nasal que mejora las proporciones y la función.',
			'Nose reshaping surgery that refines proportions and function.' => 'Cirugía de remodelación nasal que mejora las proporciones y la función.',
			'BBL (Brazilian Butt Lift)' => 'BBL (lifting brasileño de glúteos)',
			'Brazilian Butt Lift — natural contouring with fat transfer.' => 'Lifting brasileño de glúteos: remodelación natural mediante transferencia de grasa.',
			'Natural body contouring with fat transfer to the buttocks.' => 'Remodelación corporal natural mediante transferencia de grasa a los glúteos.',
			'Facelift' => 'Lifting facial',
			'Face & Neck Lift Surgery' => 'Lifting facial y de cuello',
			'Restores facial contour and reduces visible signs of aging.' => 'Recupera el contorno facial y reduce los signos visibles del envejecimiento.',
			'Breast Aesthetics' => 'Cirugía mamaria',
			'Augmentation, lift and reduction tailored to your goals.' => 'Aumento, elevación y reducción mamaria adaptados a tus objetivos.',
			'Augmentation, lift, and reduction tailored to your goals.' => 'Aumento, elevación y reducción mamaria adaptados a tus objetivos.',
			'Abdominoplasty (Tummy Tuck)' => 'Abdominoplastia',
			'Flattens and tightens the abdomen for a smoother profile.' => 'Aplana y reafirma el abdomen para conseguir un perfil más armonioso.',
			'Liposuction' => 'Liposucción',
			'Removes localized fat deposits to reshape the body.' => 'Elimina depósitos de grasa localizada para remodelar el cuerpo.',
			'Gynecomastia' => 'Ginecomastia',
			'Surgical treatment of enlarged male breast tissue.' => 'Tratamiento quirúrgico del aumento del tejido mamario masculino.',
			'Obesity Surgeries (Bariatric)' => 'Cirugía de la obesidad (bariátrica)',
			'Bariatric surgery and gastric balloon for sustainable weight loss.' => 'Cirugía bariátrica y balón gástrico para una pérdida de peso sostenible.',
			'Dental Implant' => 'Implante dental',
			'Dental Implants' => 'Implantes dentales',
			'Permanent replacement for missing teeth with titanium roots.' => 'Sustitución permanente de dientes perdidos mediante raíces de titanio.',
			'Smile Design' => 'Diseño de sonrisa',
			'A bespoke makeover that reshapes your entire smile.' => 'Una transformación a medida que rediseña toda tu sonrisa.',
			'A bespoke makeover that reshapes your smile aesthetic.' => 'Una transformación a medida que rediseña la estética de tu sonrisa.',
			'Hollywood Smile' => 'Hollywood Smile',
			'Veneers' => 'Carillas dentales',
			'Thin porcelain shells for a flawless front-of-tooth finish.' => 'Finas láminas de porcelana para un acabado impecable en la cara visible de los dientes.',
			'Teeth Whitening' => 'Blanqueamiento dental',
			'Professional bleaching for noticeably brighter teeth.' => 'Blanqueamiento profesional para unos dientes visiblemente más luminosos.',
			'Female Hair Transplant' => 'Trasplante capilar femenino',
			'Special for women, dense and natural-looking hair transplant without shaving.' => 'Trasplante sin rasurado específico para mujeres, con un resultado denso y natural.',
			'Eyebrow Transplant' => 'Trasplante de cejas',
			'Eyebrow transplantation that gives a naturally curved and full eyebrow shape.' => 'Trasplante que proporciona a las cejas una forma curva, densa y natural.',
			'Beard Transplant' => 'Trasplante de barba',
			'Natural beard and mustache transplantation for sparse or non-existing growth.' => 'Trasplante natural de barba y bigote para zonas con crecimiento escaso o inexistente.',
			'Hair Mesotherapy' => 'Mesoterapia capilar',
			'A vitamin and mineral injection treatment that revitalizes hair follicles.' => 'Tratamiento con inyecciones de vitaminas y minerales que revitaliza los folículos capilares.',
			'Pre-Hair Transplant Period' => 'Periodo previo al trasplante capilar',
			'The preparation and analysis process before hair transplantation.' => 'El proceso de preparación y análisis antes del trasplante capilar.',
			'Post-Hair Transplant Period' => 'Periodo posterior al trasplante capilar',
			'The post-procedure recovery and hair care period.' => 'El periodo de recuperación y cuidado capilar después del procedimiento.',
			'AI Analysis by Estecapelli' => 'Análisis con IA de Estecapelli',
			'Advanced AI-powered hair analysis system that examines the hair and scalp in detail.' => 'Sistema avanzado de análisis capilar con IA que examina en detalle el cabello y el cuero cabelludo.',
			'We have trained an AI to guide every patient to the best next step — get a first, personalised hair-loss assessment in seconds.' => 'Hemos entrenado una IA para guiar a cada paciente hacia el siguiente paso más adecuado: recibe en segundos una primera evaluación personalizada de la caída.',
			'Skin Rejuvenation' => 'Rejuvenecimiento de la piel',
			'Non-surgical protocols for firmer, brighter, healthier skin.' => 'Protocolos no quirúrgicos para una piel más firme, luminosa y saludable.',
			'Botox' => 'Bótox',
			'Smooths expression lines for a refreshed, rested look.' => 'Suaviza las líneas de expresión para conseguir un aspecto más fresco y descansado.',
			'Dermal Fillers' => 'Rellenos dérmicos',
			'Restores volume to cheeks, jawline and under-eye areas.' => 'Recupera el volumen de las mejillas, la línea mandibular y la zona bajo los ojos.',
			'PRP Treatment' => 'Tratamiento PRP',
			'Platelet-rich plasma therapy for skin and hair regeneration.' => 'Terapia con plasma rico en plaquetas para regenerar la piel y el cabello.',

			// Hair-analysis details and patient stories.
			'We trained our AI on the results of more than 15,000 patients. Learning from their success stories, it analyses your condition and guides you to the treatment that fits you best.' => 'Entrenamos nuestra IA con los resultados de más de 15.000 pacientes. Al aprender de sus casos de éxito, analiza tu situación y te guía hacia el tratamiento más adecuado para ti.',
			'Mark the areas where you are losing hair and tell us about your goals.' => 'Marca las zonas donde estás perdiendo cabello y cuéntanos tus objetivos.',
			'We take your photos and analyse your hair condition with an AI we have specially trained.' => 'Analizamos tus fotografías y el estado de tu cabello con una IA que hemos entrenado especialmente.',
			'A denser frontal hairline and a fuller crown.' => 'Una línea frontal más densa y una coronilla con mayor cobertura.',
			'A natural hairline with balanced front-to-crown density.' => 'Una línea frontal natural con densidad equilibrada hasta la coronilla.',
			'Frontal density extended through the mid-scalp.' => 'Densidad frontal extendida por la zona media.',
			'Frontal density extended toward the mid-scalp.' => 'Densidad frontal extendida hacia la zona media.',
			'Full-coverage restoration in a single session.' => 'Restauración con cobertura completa en una sola sesión.',
			'Hairline redesigned, density restored from front to crown.' => 'Línea frontal rediseñada y densidad recuperada desde la parte frontal hasta la coronilla.',
			'Stronger density across front, mid-scalp and crown.' => 'Mayor densidad en la zona frontal, media y la coronilla.',
			'Ireland' => 'Irlanda',
			'Scotland' => 'Escocia',
			'England' => 'Inglaterra',
			'Canada' => 'Canadá',
			'Alexandre came to our clinic from Ireland to redesign his hairline and improve density across the frontal area, mid-scalp and crown. Based on his desired hair model and donor capacity, we prioritised a natural, face-appropriate hairline first, then a balanced, homogeneous distribution through the mid-scalp and crown. The procedure was performed with the DHI Vita technique in a single session, transplanting 5,000 grafts in total — around 3,000 in the frontal area and hairline and roughly 2,000 across the mid-scalp and crown. The operation progressed normally, with PRP support applied at the end.' => 'Alexandre viajó desde Irlanda para rediseñar su línea frontal y mejorar la densidad en las zonas frontal, media y la coronilla. Según el modelo deseado y la capacidad donante, priorizamos una línea frontal natural y adecuada para su rostro, seguida de una distribución equilibrada y homogénea. El procedimiento DHI Vita se realizó en una sola sesión con 5.000 injertos: unos 3.000 en la zona frontal y la línea capilar y aproximadamente 2.000 en la zona media y la coronilla. La intervención transcurrió con normalidad y finalizó con apoyo PRP.',
			'Craig came to our clinic from Scotland to improve his hairline and increase density across the frontal area and crown. Based on his hair model and consultation plan, we prioritised a denser, more natural frontal hairline first, then a homogeneous graft distribution through the top and crown to cover the visible gaps. The procedure was performed with the FUE Vita technique in a single session, transplanting 5,400 grafts in total. Grafts were extracted evenly from the donor area with good quality, then implanted with attention to natural direction, density balance and overall coverage. The operation progressed normally, with PRP support applied at the end.' => 'Craig viajó desde Escocia para mejorar su línea frontal y aumentar la densidad en la zona frontal y la coronilla. Según su modelo de cabello y el plan de consulta, priorizamos una línea frontal más densa y natural y distribuimos después los injertos de forma homogénea por la parte superior y la coronilla. La técnica FUE Vita se realizó en una sola sesión con 5.400 injertos de buena calidad, implantados respetando la dirección natural, el equilibrio de la densidad y la cobertura general. La intervención finalizó con apoyo PRP.',
			'Dale came to our clinic from England to increase density across the frontal area, mid-scalp and crown. Based on his consultation plan and donor capacity, we focused on building stronger density in the front and crown first, while balancing the mid-scalp for an even result. The procedure was performed with the Vita protocol in a single session, transplanting 4,500 grafts in total. With a good-density donor area, the grafts were distributed to the planned coverage needs — higher density prioritised in the frontal area and crown, and the mid-scalp reinforced for a more homogeneous overall look. PRP support was applied at the end of the procedure.' => 'Dale viajó desde Inglaterra para aumentar la densidad en las zonas frontal, media y la coronilla. Según el plan y la capacidad donante, reforzamos primero la parte frontal y la coronilla y equilibramos la zona media para lograr un resultado uniforme. El protocolo Vita se realizó en una sola sesión con 4.500 injertos, distribuidos según las necesidades de cobertura y priorizando una mayor densidad en las zonas frontal y coronilla. Al final del procedimiento se aplicó apoyo PRP.',
			'Danny came to our clinic from England to improve density in his frontal area and extend coverage toward the mid-scalp. Based on his consultation plan, we prioritised harvesting the maximum number of grafts and building a dense, natural-looking result in the thinning zones, aiming for good density up to the midsection. The procedure was performed with the FUE Vita technique in a single session, transplanting 5,000 grafts in total. Grafts were extracted homogeneously from the donor area with good quality, then implanted with attention to natural direction, density balance and frontal-to-mid-scalp coverage. The operation progressed normally, with PRP support applied at the end.' => 'Danny viajó desde Inglaterra para mejorar la densidad frontal y extender la cobertura hacia la zona media. Según su plan, priorizamos la extracción del máximo número de injertos y un resultado denso y natural en las zonas con pérdida. La técnica FUE Vita se realizó en una sola sesión con 5.000 injertos de buena calidad, extraídos de forma homogénea e implantados respetando la dirección natural, el equilibrio de la densidad y la cobertura frontal y media. La intervención finalizó con apoyo PRP.',
			'Pascal came to our clinic from Canada to improve density in his frontal area and extend coverage toward the mid-scalp. Based on his consultation plan and donor capacity, we planned maximum graft extraction to cover the frontal area up to the midsection with good density, with a second session planned for full coverage. The procedure was performed with the Exosome FUE technique, transplanting 5,000 grafts in this session. Grafts were extracted homogeneously from the donor area with good hair quality, then implanted with attention to natural direction, density balance and frontal-to-mid-scalp coverage. PRP support was applied at the end of the procedure.' => 'Pascal viajó desde Canadá para mejorar la densidad frontal y extender la cobertura hacia la zona media. Según el plan y la capacidad donante, programamos la máxima extracción posible para cubrir con buena densidad la zona frontal hasta la parte media, con una segunda sesión prevista para completar la cobertura. En esta sesión se implantaron 5.000 injertos mediante Exosome FUE, respetando la dirección natural y el equilibrio de la densidad. Al final se aplicó apoyo PRP.',
			'Ricardo came to our clinic from Ireland to restore a natural hairline and improve density across the frontal area, temples and a small thinning area on the crown. Based on his consultation plan and his wish for a natural-looking result, we adjusted the frontal line to his facial structure and planned dense implantation in the front, with additional grafts placed in the temples and crown for overall balance. The procedure was performed with the DHI Vita technique in a single session, transplanting approximately 4,200 grafts. The grafts were extracted with good hair quality, then implanted with attention to natural direction, symmetry, density balance and frontal-to-crown coverage. The operation progressed normally, with PRP support at the end.' => 'Ricardo viajó desde Irlanda para recuperar una línea frontal natural y mejorar la densidad en la zona frontal, las sienes y una pequeña zona de la coronilla. Adaptamos la línea frontal a la estructura de su rostro y planificamos una implantación densa delante con injertos adicionales en las sienes y la coronilla. La técnica DHI Vita se realizó en una sola sesión con unos 4.200 injertos, implantados respetando la dirección natural, la simetría y el equilibrio de la densidad. La intervención finalizó con apoyo PRP.',
			'Sam came to our clinic from Ireland to improve his hairline and increase overall density across the frontal area, mid-scalp and crown. Based on his consultation plan and his wish for full coverage in a single session, we planned maximum graft extraction and focused on building good density in the frontal hairline first, then distributed the remaining grafts through the mid-scalp and crown for balanced coverage. The procedure was performed with the FUE Vita technique in a single session, transplanting 6,200 grafts in total. Grafts were extracted homogeneously from the donor area with good quality, then implanted with attention to natural direction, density balance and overall coverage. The operation progressed normally, with PRP support at the end.' => 'Sam viajó desde Irlanda para mejorar su línea frontal y aumentar la densidad general en las zonas frontal, media y la coronilla. Para lograr cobertura completa en una sola sesión, planificamos la máxima extracción posible, priorizamos una buena densidad en la línea frontal y distribuimos los injertos restantes por la zona media y la coronilla. La técnica FUE Vita se realizó con 6.200 injertos de buena calidad, implantados respetando la dirección natural y el equilibrio de la densidad. La intervención finalizó con apoyo PRP.',

			// Signature-card long descriptions.
			'Our patented Exosome Treatment is derived from mesenchymal stem cells found in the umbilical cord — designed to lift hair-follicle survival to 98% over 72 hours, with faster recovery, stronger growth, and naturally lasting results.' => 'Nuestro tratamiento Exosome patentado deriva de células madre mesenquimales del cordón umbilical y está diseñado para elevar la supervivencia folicular hasta el 98 % durante más de 72 horas, con una recuperación más rápida, un crecimiento más fuerte y resultados naturales y duraderos.',
			'TrichoLab examines your hair and scalp with millimetric accuracy — measuring follicle density, thickness, donor capacity, and loss patterns — so every graft is planned for your unique anatomy and the result feels naturally yours.' => 'TrichoLab examina tu cabello y cuero cabelludo con precisión milimétrica y mide la densidad folicular, el grosor, la capacidad donante y el patrón de caída para planificar cada injerto según tu anatomía y conseguir un resultado naturalmente tuyo.',
			'Grafts lose strength the moment they leave the body. Our VITA Protocol bathes them in a specially formulated vitamin cocktail with cool-vapor application — keeping every follicle alive, nourished, and resilient until placement.' => 'Los injertos empiezan a perder vitalidad al salir del cuerpo. Nuestro protocolo VITA los mantiene en un cóctel vitamínico especialmente formulado y aplicado con vapor frío, conservando cada folículo vivo, nutrido y resistente hasta su implantación.',
		);
	}

	return $strings[ $text ] ?? $translation;
}

add_filter( 'ngettext', 'estecapelli_es_ngettext_fallback', 25, 5 );
/** Translate pluralised template labels without changing article content. */
function estecapelli_es_ngettext_fallback( $translation, $single, $plural, $number, $domain ) {
	if (
		'estecapelli' === $domain &&
		estecapelli_is_spanish_request() &&
		in_array( $translation, array( $single, $plural ), true )
	) {
		if ( '%d min read' === $single && '%d min read' === $plural ) {
			return '%d min de lectura';
		}
		if ( '%d star' === $single && '%d stars' === $plural ) {
			return 1 === (int) $number ? '%d estrella' : '%d estrellas';
		}
	}

	return $translation;
}
