<?php
/**
 * Italian fallbacks for front-end theme strings.
 *
 * WPML String Translation and compiled language files remain authoritative:
 * these values are used only when the current translation is still identical
 * to its English source. This closes template-level gaps on Home, Blog,
 * Contact, Before/After, doctor profiles and shared forms without replacing
 * any editorial translation already saved in WordPress.
 *
 * @package Estecapelli
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_filter( 'gettext', 'estecapelli_it_gettext_fallback', 25, 3 );
/** Supply Italian only when no earlier translation provider changed the text. */
function estecapelli_it_gettext_fallback( $translation, $text, $domain ) {
	if ( 'estecapelli' !== $domain || $translation !== $text || ! estecapelli_is_italian_request() ) {
		return $translation;
	}

	static $strings = null;
	if ( null === $strings ) {
		$strings = array(
		// Shared navigation, footer and lead forms.
		'Skip to content' => 'Vai al contenuto',
		'Primary' => 'Navigazione principale',
		'Toggle menu' => 'Apri o chiudi il menu',
		'Choose language. Current language: %s' => 'Scegli la lingua. Lingua attuale: %s',
		'Free Consultation' => 'Consulenza gratuita',
		'Book a consultation' => 'Prenota una consulenza',
		'Ready to start your transformation?' => 'Pronto a iniziare la tua trasformazione?',
		'Speak with our medical team — free, no obligation. Get a personalized plan based on your goals.' => 'Parla gratuitamente e senza impegno con il nostro team medico. Ricevi un piano personalizzato in base ai tuoi obiettivi.',
		'Get a Free Consultation' => 'Richiedi una consulenza gratuita',
		'Chat on WhatsApp' => 'Chatta su WhatsApp',
		'Our Licences' => 'Le nostre certificazioni',
		'Sitemap' => 'Mappa del sito',
		'Language' => 'Lingua',
		'Get a free consultation — leave your details and we will reach out.' => 'Richiedi una consulenza gratuita: lascia i tuoi dati e ti contatteremo.',
		'Name and surname' => 'Nome e cognome',
		'Phone number' => 'Numero di telefono',
		'Request Call Back' => 'Richiedi di essere richiamato',
		'All rights reserved.' => 'Tutti i diritti riservati.',
		'Footer legal' => 'Link legali nel piè di pagina',
		'Privacy Policy' => 'Informativa sulla privacy',
		'Terms' => 'Termini e condizioni',
		'Cookie Policy' => 'Informativa sui cookie',
		'KVKK Notice' => 'Informativa KVKK',
		'Free Hair Analysis' => 'Analisi gratuita dei capelli',
		'Reply in 2 minutes' => 'Risposta in 2 minuti',
		'Photo viewer' => 'Visualizzatore di immagini',
		'Close' => 'Chiudi',
		'Previous photo' => 'Foto precedente',
		'Next photo' => 'Foto successiva',
		'Book your free consultation' => 'Prenota la tua consulenza gratuita',
		'Leave your details and a medical consultant will get back to you shortly — no obligation.' => 'Lascia i tuoi dati: un consulente medico ti ricontatterà al più presto, senza impegno.',
		'Full name' => 'Nome e cognome',
		'Phone' => 'Telefono',
		'Note' => 'Note',
		'Tell us about your goals, or any questions you have…' => 'Raccontaci i tuoi obiettivi o scrivi le tue domande…',
		'Request a Free Consultation' => 'Richiedi una consulenza gratuita',
		'Thank you! Your request has been received — our team will contact you shortly.' => 'Grazie! Abbiamo ricevuto la tua richiesta e il nostro team ti contatterà a breve.',
		'Hello Estecapelli, I would like to book a free consultation.' => 'Salve Estecapelli, vorrei prenotare una consulenza gratuita.',

		// Blog landing and cards. Article content deliberately remains untouched.
		'From the Journal' => 'Dal nostro magazine',
		'Research, results & recovery' => 'Ricerca, risultati e recupero',
		'Expert articles on hair restoration, plastic surgery, dental treatment and the journey to your transformation — written by the Estecapelli team.' => 'Approfondimenti degli esperti sul trapianto di capelli, la chirurgia plastica, i trattamenti dentali e il percorso verso la tua trasformazione, a cura del team Estecapelli.',
		'Article categories' => 'Categorie degli articoli',
		'All' => 'Tutti',
		'Latest article' => 'Ultimo articolo',
		'Read the article' => 'Leggi l’articolo',
		'Read more' => 'Leggi di più',
		'Posts pagination' => 'Paginazione degli articoli',
		'Newer' => 'Più recenti',
		'Older' => 'Meno recenti',
		'No articles have been published yet. New posts will appear here as soon as our team publishes them.' => 'Non è stato ancora pubblicato alcun articolo. I nuovi contenuti appariranno qui appena saranno disponibili.',
		'Research, results and recovery — written by our team.' => 'Ricerca, risultati e recupero, raccontati dal nostro team.',
		'View all articles' => 'Visualizza tutti gli articoli',

		// Contact page.
		'Hello Estecapelli, I would like a free analysis. Here are my photos:' => 'Salve Estecapelli, vorrei ricevere un’analisi gratuita. Ecco le mie foto:',
		'English' => 'Inglese',
		'French' => 'Francese',
		'Italian' => 'Italiano',
		'Spanish' => 'Spagnolo',
		'Polish' => 'Polacco',
		'Portuguese' => 'Portoghese',
		'Contact Us' => 'Contattaci',
		'Let’s start your journey' => 'Iniziamo il tuo percorso',
		'Reach our team by WhatsApp, phone or email — or leave your details and a medical consultant will get back to you in your own language.' => 'Contatta il nostro team tramite WhatsApp, telefono o e-mail, oppure lascia i tuoi dati: un consulente medico ti risponderà nella tua lingua.',
		'We usually reply within an hour' => 'Di solito rispondiamo entro un’ora',
		'Chat with us now' => 'Chatta subito con noi',
		'Call' => 'Chiama',
		'Request a free consultation' => 'Richiedi una consulenza gratuita',
		'Tell us a little about you and we’ll be in touch shortly.' => 'Raccontaci brevemente le tue esigenze e ti contatteremo al più presto.',
		'Interested in' => 'Trattamento di interesse',
		'Select a treatment' => 'Seleziona un trattamento',
		'Hair Transplant' => 'Trapianto di capelli',
		'Plastic Surgery' => 'Chirurgia plastica',
		'Dental Treatment' => 'Trattamento dentale',
		'Not sure yet' => 'Non sono ancora sicuro',
		'Message' => 'Messaggio',
		'Send Request' => 'Invia la richiesta',
		'Please enter a valid phone number.' => 'Inserisci un numero di telefono valido.',
		'Please enter a valid email address.' => 'Inserisci un indirizzo e-mail valido.',
		'Please enter your name.' => 'Inserisci il tuo nome.',
		'Name is required.' => 'Il nome è obbligatorio.',
		'Please enter your phone number.' => 'Inserisci il tuo numero di telefono.',
		'Please select a valid country code.' => 'Seleziona un prefisso internazionale valido.',
		'This number is too short for the selected country.' => 'Questo numero è troppo corto per il paese selezionato.',
		'This number is too long for the selected country.' => 'Questo numero è troppo lungo per il paese selezionato.',
		'Please enter the full phone number, including the area code.' => 'Inserisci il numero di telefono completo, prefisso incluso.',
		'Please enter a valid phone number for the selected country.' => 'Inserisci un numero di telefono valido per il paese selezionato.',
		'Visit & reach us' => 'Vieni a trovarci o contattaci',
		'Address' => 'Indirizzo',
		'Working hours' => 'Orari di apertura',
		'Monday – Sunday: 09:00 – 18:00 (GMT+3)' => 'Lunedì – domenica: 09:00 – 18:00 (GMT+3)',
		'What happens next?' => 'Cosa succede dopo?',
		'We review your request and reach out to understand your goals.' => 'Esaminiamo la tua richiesta e ti contattiamo per comprendere i tuoi obiettivi.',
		'You receive a free, personalised treatment plan and quote.' => 'Ricevi gratuitamente un piano di trattamento e un preventivo personalizzati.',
		'We arrange your dates, travel and stay — and welcome you to Istanbul.' => 'Organizziamo date, viaggio e soggiorno e ti accogliamo a Istanbul.',
		'Send your photos, get a free analysis' => 'Invia le tue foto e ricevi un’analisi gratuita',
		'Share a few photos of your hair, face or smile and our specialists will assess your case and recommend the right approach — at no cost and with no obligation.' => 'Condividi alcune foto dei capelli, del viso o del sorriso: i nostri specialisti valuteranno il tuo caso e consiglieranno l’approccio più adatto, gratuitamente e senza impegno.',
		'Send Photos on WhatsApp' => 'Invia le foto su WhatsApp',
		'Talk to us in your own language' => 'Parla con noi nella tua lingua',
		'Estecapelli clinic location' => 'Posizione della clinica Estecapelli',

		// Before/After and gallery UI.
		'Before' => 'Prima',
		'After' => 'Dopo',
		'Before & After' => 'Prima e dopo',
		'Before treatment' => 'Prima del trattamento',
		'After treatment' => 'Dopo il trattamento',
		'%s grafts' => '%s innesti',
		'Before and after results' => 'Risultati prima e dopo',
		'Real Results' => 'Risultati reali',
		'Before &amp; After' => 'Prima e dopo',
		'Outcomes from our %s patients.' => 'Risultati dei nostri pazienti sottoposti a %s.',
		'Previous result' => 'Risultato precedente',
		'Next result' => 'Risultato successivo',
		'Results will appear here soon.' => 'I risultati saranno disponibili qui a breve.',
		'Treatment categories' => 'Categorie di trattamento',
		'%s services' => 'Servizi di %s',
		'View treatment' => 'Visualizza il trattamento',
		'Enlarge result' => 'Ingrandisci il risultato',
		'Before and after result' => 'Risultato prima e dopo',
		'grafts' => 'innesti',
		'See full gallery' => 'Visualizza la galleria completa',

		// Doctor pages and reusable sections.
		'Résumé' => 'Curriculum',
		'Book a Free Consultation' => 'Prenota una consulenza gratuita',
		'View Résumé' => 'Visualizza il curriculum',
		'Meet the doctor' => 'Conosci il medico',
		'Languages spoken' => 'Lingue parlate',
		'Procedure quick facts' => 'Informazioni rapide sulla procedura',
		'Get Started' => 'Inizia ora',
		'Learn More' => 'Scopri di più',
		'Learn more' => 'Scopri di più',

		// Homepage hero and service discovery.
		'Highlights' => 'In evidenza',
		'Signature Methods' => 'Metodi esclusivi',
		'Select a method to play' => 'Seleziona un metodo per riprodurre il video',
		'World-Class Experience' => 'Esperienza di livello mondiale',
		'Estecapelli patient result' => 'Risultato di un paziente Estecapelli',
		'Previous patient' => 'Paziente precedente',
		'Next patient' => 'Paziente successivo',
		'Estecapelli Dental' => 'Estecapelli Dental',
		'Estecapelli dental patient smiling' => 'Paziente Estecapelli Dental sorridente',
		'A Smile Designed Around You' => 'Un sorriso progettato intorno a te',
		'Hollywood smiles, veneers and full-mouth restorations — crafted by our specialists for a natural, confident result that lasts.' => 'Hollywood Smile, faccette e riabilitazioni complete realizzate dai nostri specialisti per un risultato naturale, sicuro e duraturo.',
		'Hollywood Smile & porcelain veneers' => 'Hollywood Smile e faccette in porcellana',
		'Implants & full-mouth restoration' => 'Impianti e riabilitazione completa',
		'One trusted clinic, all-inclusive care' => 'Un’unica clinica affidabile, assistenza tutto incluso',
		'Explore Dental Treatments' => 'Scopri i trattamenti dentali',
		'Previous slide' => 'Slide precedente',
		'Next slide' => 'Slide successiva',
		'Choose slide' => 'Scegli la slide',
		'Slide %d' => 'Slide %d',
		'OUR SIGNATURE METHODS' => 'I NOSTRI METODI ESCLUSIVI',
		'Two techniques. Registered to our name.' => 'Due tecniche registrate a nostro nome.',
		'Two exclusive, trademarked protocols — developed in-house.' => 'Due protocolli esclusivi e registrati, sviluppati internamente.',
		'Treatment' => 'Trattamento',
		'Explore VITA®' => 'Scopri VITA®',
		'Explore Exosome®' => 'Scopri Exosome®',
		'EST. 2010 · ISTANBUL' => 'DAL 2010 · ISTANBUL',
		'One of the World’s Most Experienced Hair Restoration Teams' => 'Uno dei team più esperti al mondo nel ripristino dei capelli',
		'Join the thousands who have come to Estecapelli to regain their confidence.' => 'Unisciti alle migliaia di pazienti che hanno scelto Estecapelli per ritrovare fiducia in sé.',
		'Schedule a Free Consultation' => 'Prenota una consulenza gratuita',
		'Over 50,000+' => 'Oltre 50.000',
		'5-Star Results' => 'Risultati a 5 stelle',
		'Actual Estecapelli patient. Individual results may vary.' => 'Paziente reale Estecapelli. I risultati individuali possono variare.',
		'FIFTEEN YEARS' => 'QUINDICI ANNI',
		'FOR WOMEN · DISCREET & NATURAL' => 'PER LE DONNE · DISCRETO E NATURALE',
		'Women’s Hair Transplant in Istanbul' => 'Trapianto di capelli femminile a Istanbul',
		'Thinning along the parting, a receding hairline or overall loss of density affects women too. Our female-focused approach restores fullness with unshaven techniques, complete privacy and natural, permanent results.' => 'Diradamento lungo la scriminatura, arretramento dell’attaccatura o perdita diffusa di densità riguardano anche le donne. Il nostro approccio dedicato ripristina la pienezza con tecniche senza rasatura, massima riservatezza e risultati naturali e permanenti.',
		'Unshaven, discreet techniques' => 'Tecniche discrete senza rasatura',
		'Natural hairline & density design' => 'Progettazione naturale di attaccatura e densità',
		'Female patient privacy at every step' => 'Massima privacy in ogni fase',
		'Years of Experience' => 'Anni di esperienza',
		'Happy Patients' => 'Pazienti soddisfatti',
		'Countries Served' => 'Paesi serviti',
		'Support Team' => 'Team di assistenza',
		'What We Treat' => 'I nostri trattamenti',
		'Pick a field. See our signature treatments.' => 'Scegli un’area e scopri i nostri trattamenti distintivi.',
		'Switch between tabs to explore the methods we are best known for in each field of care.' => 'Passa da una scheda all’altra per scoprire i metodi che ci distinguono in ogni area di cura.',
		'Previous treatments' => 'Trattamenti precedenti',
		'Next treatments' => 'Trattamenti successivi',

		// Homepage supporting sections.
		'The Comparison' => 'Il confronto',
		'Global standards, Turkish expertise.' => 'Standard internazionali, esperienza turca.',
		'See how our comprehensive approach and advanced techniques set us apart from other clinics.' => 'Scopri come il nostro approccio completo e le tecniche avanzate ci distinguono dalle altre cliniche.',
		'Built for patients who refuse to compromise.' => 'Pensato per chi non accetta compromessi.',
		'At Estecapelli, we go beyond expectations to deliver personalised, high-quality care backed by years of experience and international standards. Our expert team combines innovative methods with a patient-first approach to deliver results that look natural and feel confident.' => 'Estecapelli supera le aspettative offrendo cure personalizzate e di alta qualità, sostenute da anni di esperienza e standard internazionali. Il nostro team combina metodi innovativi e attenzione al paziente per ottenere risultati naturali e sicuri.',
		'Experience the Estecapelli difference — advanced techniques, patient-focused care.' => 'Scopri la differenza Estecapelli: tecniche avanzate e assistenza centrata sul paziente.',
		'Other Clinics' => 'Altre cliniche',
		'Premium Care' => 'Assistenza premium',
		'Standard Care' => 'Assistenza standard',
		'5-Star Hotel Accommodation' => 'Soggiorno in hotel a 5 stelle',
		'VIP Transfer Service' => 'Servizio transfer VIP',
		'Personal Translator' => 'Interprete personale',
		'Latest Technology Implementation' => 'Tecnologie di ultima generazione',
		'Success-Oriented Treatment Planning' => 'Pianificazione orientata al risultato',
		'Innovative Techniques (Exosome, FUE, DHI, VITA)' => 'Tecniche innovative (Exosome, FUE, DHI, VITA)',
		'Regenerative Stem Cell Therapy' => 'Terapia rigenerativa con cellule staminali',
		'Dedicated Post-Op Follow-Up Team' => 'Team dedicato al follow-up postoperatorio',
		'Pain-Free Anaesthesia' => 'Anestesia senza dolore',
		'Nine details where every choice matters.' => 'Nove dettagli in cui ogni scelta conta.',
		'Our Expertise' => 'La nostra esperienza',
		'Three methods that shape every treatment.' => 'Tre metodi che guidano ogni trattamento.',
		'Two are exclusively ours. One sets the standard for personalised planning. All three power the results our patients trust us for.' => 'Due sono esclusivamente nostri e uno definisce lo standard della pianificazione personalizzata. Tutti e tre contribuiscono ai risultati per cui i pazienti ci scelgono.',
		'Patented · Estecapelli Exclusive' => 'Brevettato · Esclusiva Estecapelli',
		'Premium Hair Transplant Method' => 'Metodo premium di trapianto di capelli',
		'Mesenchymal stem-cell support that keeps follicles alive longer.' => 'Supporto con cellule staminali mesenchimali per mantenere vitali i follicoli più a lungo.',
		'Follicle survival over 72 hours' => 'Sopravvivenza follicolare oltre 72 ore',
		'Learn about Exosome FUE' => 'Scopri Exosome FUE',
		'AI-Powered Diagnosis' => 'Diagnosi supportata dall’IA',
		'Millimetric Hair & Scalp Analysis' => 'Analisi millimetrica di capelli e cuoio capelluto',
		'AI maps your scalp before a single graft is planned.' => 'L’IA analizza il cuoio capelluto prima di pianificare ogni singolo innesto.',
		'Millimetric' => 'Millimetrica',
		'Precision per scalp scan' => 'Precisione in ogni scansione del cuoio capelluto',
		'Learn more about TrichoLab' => 'Scopri di più su TrichoLab',
		'Signature Protocol · Estecapelli Exclusive' => 'Protocollo esclusivo · Esclusiva Estecapelli',
		'Power Derived from Vitamins' => 'La forza delle vitamine',
		'A vitamin-cooled bath that keeps grafts strong out of the body.' => 'Una soluzione vitaminica raffreddata che mantiene forti gli innesti fuori dal corpo.',
		'Cool-Vapor' => 'Vapore freddo',
		'Vitamin-nourished grafts' => 'Innesti nutriti con vitamine',
		'Learn more about VITA' => 'Scopri di più su VITA',
		'Real Stories' => 'Storie reali',
		'Their results speak louder than any ad ever could.' => 'I loro risultati parlano più di qualsiasi pubblicità.',
		'Hear, in their own words, how patients from around the world describe their Estecapelli journey — from first consultation to long-term result.' => 'Ascolta direttamente dai pazienti di tutto il mondo il loro percorso con Estecapelli, dalla prima consulenza al risultato nel tempo.',
		'Grafts' => 'Innesti',
		'Technique' => 'Tecnica',
		'Patient from' => 'Paziente da',
		'More patient stories' => 'Altre storie dei pazienti',
		'On the playlist' => 'Nella playlist',
		'Our Clinic' => 'La nostra clinica',
		'Step inside our Istanbul clinic' => 'Entra nella nostra clinica di Istanbul',
		'A Ministry-of-Health licensed, hospital-grade facility in the heart of Istanbul — modern operation rooms, sterile theatres and a permanent on-site medical team.' => 'Una struttura di livello ospedaliero autorizzata dal Ministero della Salute, nel cuore di Istanbul, con sale operatorie moderne, ambienti sterili e un team medico presente in sede.',
		'Clinic walkthrough' => 'Visita della clinica',
		'Hair Transplant Surgery Room' => 'Sala per il trapianto di capelli',
		'TrichoLab Room' => 'Sala TrichoLab',
		'Lobby' => 'Reception',
		'Dental Clinic' => 'Clinica dentale',
		'Our partner hotels' => 'I nostri hotel partner',
		'Hair Analysis Lab' => 'Laboratorio di analisi dei capelli',
		'Your Personalised Hair Plan, Powered by Estecapelli' => 'Il tuo piano personalizzato per i capelli, sviluppato da Estecapelli',
		'I know my hair-loss area' => 'Conosco l’area interessata dalla caduta',
		'Start self-assessment' => 'Inizia l’autovalutazione',
		'Analyse my photos with AI' => 'Analizza le mie foto con l’IA',
		'Start AI Analysis' => 'Avvia l’analisi con IA',
		'Back to options' => 'Torna alle opzioni',
		'Tap the areas where you are losing hair' => 'Tocca le aree in cui stai perdendo capelli',
		'Selected areas' => 'Aree selezionate',
		'No area selected yet.' => 'Nessuna area ancora selezionata.',
		'Your name' => 'Il tuo nome',
		'Phone / WhatsApp' => 'Telefono / WhatsApp',
		'Your number' => 'Il tuo numero',
		'Your email' => 'La tua e-mail',
		'Get my analysis' => 'Ricevi la mia analisi',
		'Real Patients · Real Results' => 'Pazienti reali · Risultati reali',
		'Choose a hair-transplant technique to browse real patient results.' => 'Scegli una tecnica di trapianto per vedere i risultati di pazienti reali.',
		'Hair transplant techniques' => 'Tecniche di trapianto di capelli',
		'View all results' => 'Visualizza tutti i risultati',

		// Remaining shared accessibility and interaction copy.
		'%1$s grafts · %2$s' => '%1$s innesti · %2$s',
		'Close video' => 'Chiudi il video',
		'Back to gallery' => 'Torna alla galleria',
		'Click any photo to open the gallery' => 'Fai clic su una foto per aprire la galleria',
		'Contents' => 'Contenuti',
		'Enlarge photo' => 'Ingrandisci la foto',
		'Go to photo %d' => 'Vai alla foto %d',
		'Hover or tap to discover' => 'Passa il cursore o tocca per scoprire',
		'Included' => 'Incluso',
		'Included at Estecapelli' => 'Incluso da Estecapelli',
		'Not included' => 'Non incluso',
		'Next step' => 'Fase successiva',
		'Previous step' => 'Fase precedente',
		'Open gallery: %s' => 'Apri la galleria: %s',
		'Open the gallery' => 'Apri la galleria',
		'Play %s video' => 'Riproduci il video di %s',
		'Play %s — %s' => 'Riproduci %s — %s',
		'Procedure details' => 'Dettagli della procedura',
		'Rated %d out of 5' => 'Valutazione: %d su 5',
		'Scalp zones' => 'Zone del cuoio capelluto',
		'Scroll left' => 'Scorri a sinistra',
		'Scroll right' => 'Scorri a destra',
		'Steps' => 'Fasi',
		'Treatments' => 'Trattamenti',
		'Trustpilot rating: 5 out of 5, Excellent' => 'Valutazione Trustpilot: 5 su 5, Eccellente',
		'Use the arrows to browse · click any photo to enlarge' => 'Usa le frecce per scorrere · fai clic su una foto per ingrandirla',
		'View result %d' => 'Visualizza il risultato %d',
		'Write the first article' => 'Scrivi il primo articolo',
		'No articles have been published yet. New posts will appear here as soon as your team publishes them.' => 'Non è stato ancora pubblicato alcun articolo. I nuovi contenuti appariranno qui appena il team li pubblicherà.',
		'step' => 'fase',
		'Excellent' => 'Eccellente',
		'on Trustpilot' => 'su Trustpilot',
		'Google Reviews' => 'Recensioni Google',
		'Estecapelli in numbers' => 'Estecapelli in numeri',
		'Patients trust us by the numbers' => 'La fiducia dei pazienti in numeri',
		'Estecapelli versus other clinics — feature comparison' => 'Estecapelli e altre cliniche: confronto dei servizi',
		'Internationally Accredited & Certified' => 'Accreditata e certificata a livello internazionale',
		'Internationally accredited & certified — Ministry of Health, Certified Medical Travel Agency, HRSA, NACo Award, ISO 13485' => 'Accreditata e certificata a livello internazionale — Ministero della Salute, Agenzia certificata per il turismo medico, HRSA, premio NACo, ISO 13485',
		'Internationally accredited — Ministry of Health, HRSA, NACo, ISO 13485, Certified Medical Travel Agency' => 'Accreditata a livello internazionale — Ministero della Salute, HRSA, NACo, ISO 13485, Agenzia certificata per il turismo medico',
		'Internationally accredited — Ministry of Health, HRSA, NACo, ISO 13485, Certified Medical Travel Agent' => 'Accreditata a livello internazionale — Ministero della Salute, HRSA, NACo, ISO 13485, Operatore certificato per il turismo medico',

		// Homepage fallback hero and service-card copy.
		'EST. 2010 · ISTANBUL, TÜRKİYE' => 'DAL 2010 · ISTANBUL, TURCHIA',
		'Aesthetic Excellence, Backed by Medical Trust.' => 'Eccellenza estetica sostenuta dalla fiducia medica.',
		"From hair restoration to plastic, dental and non-surgical aesthetics — Estecapelli's board-certified doctors deliver hospital-grade care with the precision your transformation deserves." => 'Dal ripristino dei capelli alla chirurgia plastica, ai trattamenti dentali e alla medicina estetica non chirurgica: i medici qualificati di Estecapelli offrono cure di livello ospedaliero con la precisione che la tua trasformazione merita.',
		'Dr. Mehmet Hanifi Kutlar' => 'Dr. Mehmet Hanifi Kutlar',
		'Medical Director & Co-founder' => 'Direttore medico e cofondatore',
		'15+ years in aesthetic medicine' => 'Oltre 15 anni nella medicina estetica',
		'ACCREDITED CLINIC' => 'CLINICA ACCREDITATA',
		'Ministry of Health Licensed' => 'Autorizzata dal Ministero della Salute',
		'ISO 9001 · TURSAB Certified' => 'Certificata ISO 9001 · TURSAB',
		'About Estecapelli' => 'Chi è Estecapelli',
		'About Us' => 'Chi siamo',
		'Who we are and what drives our clinic forward.' => 'Chi siamo e cosa guida ogni giorno la nostra clinica.',
		'Our Doctors' => 'I nostri medici',
		'Meet the surgeons leading every procedure.' => 'Conosci i chirurghi che seguono ogni intervento.',
		'Our Team' => 'Il nostro team',
		'The full medical and patient-care team behind your treatment.' => 'Il team medico e di assistenza che segue il tuo trattamento.',
		'Visit Us' => 'Vieni a trovarci',
		'Medical Treatment' => 'Trattamento medico',
		'Hair Transplant Care & Technology' => 'Cura e tecnologia per il trapianto di capelli',
		'Micro Sapphire FUE' => 'Micro Sapphire FUE',
		'Sapphire FUE Hair Transplant' => 'Trapianto di capelli Sapphire FUE',
		'Sapphire-blade precision for natural density and faster healing.' => 'Precisione delle lame in zaffiro per una densità naturale e una guarigione più rapida.',
		'A natural and permanent hair transplant technique where follicles are placed via sapphire blades.' => 'Una tecnica di trapianto naturale e permanente in cui i follicoli vengono impiantati attraverso lame in zaffiro.',
		'DHI Hair Transplant' => 'Trapianto di capelli DHI',
		'A modern hair transplantation method performed with a Choi pen that allows precise placement.' => 'Un moderno metodo di trapianto eseguito con penna Choi, che consente un impianto preciso.',
		'Choi-pen implantation for precise angle and direction control.' => 'Impianto con penna Choi per controllare con precisione angolazione e direzione.',
		'Exosome FUE Hair Transplant' => 'Trapianto di capelli Exosome FUE',
		'Exosome Treatment' => 'Trattamento Exosome',
		'Cell-regenerating exosomes that keep follicles alive longer.' => 'Esosomi rigenerativi che mantengono vitali i follicoli più a lungo.',
		'Supported by cell-regenerating exosomes, it keeps hair follicles alive for longer-lasting density.' => 'Grazie al supporto di esosomi rigenerativi, mantiene vitali i follicoli per una densità più duratura.',
		'VITA Treatment' => 'Trattamento VITA',
		"Estecapelli's signature protocol that revitalises scalp & strands." => 'Il protocollo esclusivo Estecapelli che rivitalizza cuoio capelluto e capelli.',
		"Estecapelli's signature method that revitalizes the scalp and strengthens hair." => 'Il metodo esclusivo Estecapelli che rivitalizza il cuoio capelluto e rinforza i capelli.',
		'POPULAR' => 'POPOLARE',
		'SIGNATURE' => 'ESCLUSIVO',
		'Rhinoplasty' => 'Rinoplastica',
		'Nose reshaping that refines proportions and function.' => 'Rimodellamento del naso che migliora proporzioni e funzionalità.',
		'Nose reshaping surgery that refines proportions and function.' => 'Intervento di rimodellamento del naso che migliora proporzioni e funzionalità.',
		'BBL (Brazilian Butt Lift)' => 'BBL (Brazilian Butt Lift)',
		'Brazilian Butt Lift — natural contouring with fat transfer.' => 'Brazilian Butt Lift: rimodellamento naturale mediante trasferimento di grasso.',
		'Natural body contouring with fat transfer to the buttocks.' => 'Rimodellamento naturale del corpo mediante trasferimento di grasso ai glutei.',
		'Facelift' => 'Lifting del viso',
		'Face & Neck Lift Surgery' => 'Lifting di viso e collo',
		'Restores facial contour and reduces visible signs of aging.' => 'Ripristina i contorni del viso e riduce i segni visibili dell’invecchiamento.',
		'Breast Aesthetics' => 'Chirurgia del seno',
		'Augmentation, lift and reduction tailored to your goals.' => 'Aumento, lifting e riduzione del seno personalizzati in base ai tuoi obiettivi.',
		'Augmentation, lift, and reduction tailored to your goals.' => 'Aumento, lifting e riduzione del seno personalizzati in base ai tuoi obiettivi.',
		'Abdominoplasty (Tummy Tuck)' => 'Addominoplastica',
		'Flattens and tightens the abdomen for a smoother profile.' => 'Rende l’addome più piatto e tonico per un profilo più armonioso.',
		'Liposuction' => 'Liposuzione',
		'Removes localized fat deposits to reshape the body.' => 'Rimuove gli accumuli adiposi localizzati per rimodellare il corpo.',
		'Gynecomastia' => 'Ginecomastia',
		'Surgical treatment of enlarged male breast tissue.' => 'Trattamento chirurgico dell’aumento del tessuto mammario maschile.',
		'Obesity Surgeries (Bariatric)' => 'Chirurgia dell’obesità (bariatrica)',
		'Bariatric surgery and gastric balloon for sustainable weight loss.' => 'Chirurgia bariatrica e palloncino gastrico per una perdita di peso duratura.',
		'Dental Implant' => 'Impianto dentale',
		'Dental Implants' => 'Impianti dentali',
		'Permanent replacement for missing teeth with titanium roots.' => 'Sostituzione permanente dei denti mancanti con radici in titanio.',
		'Smile Design' => 'Design del sorriso',
		'A bespoke makeover that reshapes your entire smile.' => 'Una trasformazione su misura che ridisegna l’intero sorriso.',
		'A bespoke makeover that reshapes your smile aesthetic.' => 'Una trasformazione su misura che ridisegna l’estetica del sorriso.',
		'Hollywood Smile' => 'Sorriso hollywoodiano',
		'Veneers' => 'Faccette dentali',
		'Thin porcelain shells for a flawless front-of-tooth finish.' => 'Sottili lamine in porcellana per un risultato impeccabile sulla superficie dei denti.',
		'Teeth Whitening' => 'Sbiancamento dentale',
		'Professional bleaching for noticeably brighter teeth.' => 'Sbiancamento professionale per denti visibilmente più luminosi.',
		'Female Hair Transplant' => 'Trapianto di capelli femminile',
		'Special for women, dense and natural-looking hair transplant without shaving.' => 'Trapianto senza rasatura specifico per le donne, con un risultato folto e naturale.',
		'Eyebrow Transplant' => 'Trapianto di sopracciglia',
		'Eyebrow transplantation that gives a naturally curved and full eyebrow shape.' => 'Trapianto che dona alle sopracciglia una forma piena e naturalmente arcuata.',
		'Beard Transplant' => 'Trapianto di barba',
		'Natural beard and mustache transplantation for sparse or non-existing growth.' => 'Trapianto naturale di barba e baffi nelle aree rade o prive di crescita.',
		'Hair Mesotherapy' => 'Mesoterapia per capelli',
		'A vitamin and mineral injection treatment that revitalizes hair follicles.' => 'Trattamento iniettivo a base di vitamine e minerali che rivitalizza i follicoli.',
		'Pre-Hair Transplant Period' => 'Periodo pre-trapianto di capelli',
		'The preparation and analysis process before hair transplantation.' => 'Il percorso di preparazione e analisi prima del trapianto di capelli.',
		'Post-Hair Transplant Period' => 'Periodo post-trapianto di capelli',
		'The post-procedure recovery and hair care period.' => 'Il periodo di recupero e cura dei capelli dopo la procedura.',
		'AI Analysis by Estecapelli' => 'Analisi con IA di Estecapelli',
		'Advanced AI-powered hair analysis system that examines the hair and scalp in detail.' => 'Sistema avanzato di analisi con IA che esamina in dettaglio capelli e cuoio capelluto.',
		'We have trained an AI to guide every patient to the best next step — get a first, personalised hair-loss assessment in seconds.' => 'Abbiamo addestrato un’IA per guidare ogni paziente verso il passo successivo più adatto: ricevi in pochi secondi una prima valutazione personalizzata della caduta.',
		'Skin Rejuvenation' => 'Ringiovanimento della pelle',
		'Non-surgical protocols for firmer, brighter, healthier skin.' => 'Protocolli non chirurgici per una pelle più compatta, luminosa e sana.',
		'Botox' => 'Botox',
		'Smooths expression lines for a refreshed, rested look.' => 'Attenua le rughe d’espressione per un aspetto più fresco e riposato.',
		'Dermal Fillers' => 'Filler dermici',
		'Restores volume to cheeks, jawline and under-eye areas.' => 'Ripristina i volumi di guance, mandibola e area sotto gli occhi.',
		'PRP Treatment' => 'Trattamento PRP',
		'Platelet-rich plasma therapy for skin and hair regeneration.' => 'Terapia con plasma ricco di piastrine per rigenerare pelle e capelli.',

		// Hair Analysis Lab detail copy.
		'We trained our AI on the results of more than 15,000 patients. Learning from their success stories, it analyses your condition and guides you to the treatment that fits you best.' => 'Abbiamo addestrato la nostra IA sui risultati di oltre 15.000 pazienti. Imparando dai loro percorsi di successo, analizza la tua situazione e ti guida verso il trattamento più adatto.',
		'Mark the areas where you are losing hair and tell us about your goals.' => 'Indica le aree in cui stai perdendo capelli e raccontaci i tuoi obiettivi.',
		'We take your photos and analyse your hair condition with an AI we have specially trained.' => 'Analizziamo le tue foto e la condizione dei capelli con un sistema di IA appositamente addestrato.',

		// Homepage patient stories.
		'A denser frontal hairline and a fuller crown.' => 'Un’attaccatura frontale più densa e una corona più piena.',
		'A natural hairline with balanced front-to-crown density.' => 'Un’attaccatura naturale con densità equilibrata dalla zona frontale alla corona.',
		'Frontal density extended through the mid-scalp.' => 'Maggiore densità frontale estesa fino alla zona centrale.',
		'Frontal density extended toward the mid-scalp.' => 'Densità frontale estesa verso la zona centrale.',
		'Full-coverage restoration in a single session.' => 'Ripristino completo in un’unica seduta.',
		'Hairline redesigned, density restored from front to crown.' => 'Attaccatura ridisegnata e densità ripristinata dalla zona frontale alla corona.',
		'Stronger density across front, mid-scalp and crown.' => 'Maggiore densità nella zona frontale, centrale e nella corona.',
		'Ireland' => 'Irlanda',
		'Scotland' => 'Scozia',
		'England' => 'Inghilterra',
		'Canada' => 'Canada',
		'Alexandre came to our clinic from Ireland to redesign his hairline and improve density across the frontal area, mid-scalp and crown. Based on his desired hair model and donor capacity, we prioritised a natural, face-appropriate hairline first, then a balanced, homogeneous distribution through the mid-scalp and crown. The procedure was performed with the DHI Vita technique in a single session, transplanting 5,000 grafts in total — around 3,000 in the frontal area and hairline and roughly 2,000 across the mid-scalp and crown. The operation progressed normally, with PRP support applied at the end.' => 'Alexandre è arrivato dall’Irlanda per ridisegnare l’attaccatura e aumentare la densità nella zona frontale, centrale e nella corona. In base al modello desiderato e alla capacità dell’area donatrice, abbiamo dato priorità a un’attaccatura naturale e adatta al viso, distribuendo poi gli innesti in modo equilibrato e omogeneo. La procedura DHI Vita è stata completata in un’unica seduta con 5.000 innesti: circa 3.000 nella zona frontale e nell’attaccatura e circa 2.000 nella zona centrale e nella corona. L’intervento si è svolto regolarmente ed è stato completato con supporto PRP.',
		'Craig came to our clinic from Scotland to improve his hairline and increase density across the frontal area and crown. Based on his hair model and consultation plan, we prioritised a denser, more natural frontal hairline first, then a homogeneous graft distribution through the top and crown to cover the visible gaps. The procedure was performed with the FUE Vita technique in a single session, transplanting 5,400 grafts in total. Grafts were extracted evenly from the donor area with good quality, then implanted with attention to natural direction, density balance and overall coverage. The operation progressed normally, with PRP support applied at the end.' => 'Craig è arrivato dalla Scozia per migliorare l’attaccatura e aumentare la densità nella zona frontale e nella corona. In base al suo modello di capelli e al piano definito in consulenza, abbiamo dato priorità a un’attaccatura frontale più densa e naturale, distribuendo poi gli innesti in modo omogeneo sulla parte superiore e sulla corona. La procedura FUE Vita è stata eseguita in un’unica seduta con 5.400 innesti. Gli innesti, di buona qualità, sono stati prelevati uniformemente dall’area donatrice e impiantati rispettando direzione naturale, equilibrio della densità e copertura complessiva. L’intervento si è concluso regolarmente con supporto PRP.',
		'Dale came to our clinic from England to increase density across the frontal area, mid-scalp and crown. Based on his consultation plan and donor capacity, we focused on building stronger density in the front and crown first, while balancing the mid-scalp for an even result. The procedure was performed with the Vita protocol in a single session, transplanting 4,500 grafts in total. With a good-density donor area, the grafts were distributed to the planned coverage needs — higher density prioritised in the frontal area and crown, and the mid-scalp reinforced for a more homogeneous overall look. PRP support was applied at the end of the procedure.' => 'Dale è arrivato dall’Inghilterra per aumentare la densità nella zona frontale, centrale e nella corona. In base al piano e alla capacità donatrice, abbiamo rafforzato soprattutto la zona frontale e la corona, bilanciando la parte centrale per un risultato uniforme. Il protocollo Vita è stato eseguito in un’unica seduta con 4.500 innesti. Grazie alla buona densità dell’area donatrice, gli innesti sono stati distribuiti secondo le necessità di copertura, con maggiore densità nella zona frontale e nella corona e un rinforzo centrale per un aspetto complessivamente omogeneo. Al termine è stato applicato il supporto PRP.',
		'Danny came to our clinic from England to improve density in his frontal area and extend coverage toward the mid-scalp. Based on his consultation plan, we prioritised harvesting the maximum number of grafts and building a dense, natural-looking result in the thinning zones, aiming for good density up to the midsection. The procedure was performed with the FUE Vita technique in a single session, transplanting 5,000 grafts in total. Grafts were extracted homogeneously from the donor area with good quality, then implanted with attention to natural direction, density balance and frontal-to-mid-scalp coverage. The operation progressed normally, with PRP support applied at the end.' => 'Danny è arrivato dall’Inghilterra per migliorare la densità frontale ed estendere la copertura verso la zona centrale. In base al piano di consulenza, abbiamo prelevato il maggior numero possibile di innesti per ottenere un risultato denso e naturale nelle aree diradate. La tecnica FUE Vita è stata eseguita in un’unica seduta con 5.000 innesti. Gli innesti, di buona qualità, sono stati prelevati in modo omogeneo e impiantati rispettando direzione naturale, equilibrio della densità e copertura dalla zona frontale a quella centrale. L’intervento si è concluso regolarmente con supporto PRP.',
		'Pascal came to our clinic from Canada to improve density in his frontal area and extend coverage toward the mid-scalp. Based on his consultation plan and donor capacity, we planned maximum graft extraction to cover the frontal area up to the midsection with good density, with a second session planned for full coverage. The procedure was performed with the Exosome FUE technique, transplanting 5,000 grafts in this session. Grafts were extracted homogeneously from the donor area with good hair quality, then implanted with attention to natural direction, density balance and frontal-to-mid-scalp coverage. PRP support was applied at the end of the procedure.' => 'Pascal è arrivato dal Canada per migliorare la densità frontale ed estendere la copertura verso la zona centrale. In base al piano e alla capacità dell’area donatrice, abbiamo programmato il massimo prelievo possibile per coprire con buona densità la zona frontale fino alla parte centrale, prevedendo una seconda seduta per la copertura completa. In questa seduta sono stati trapiantati 5.000 innesti con tecnica Exosome FUE. Gli innesti, di buona qualità, sono stati prelevati in modo omogeneo e impiantati rispettando direzione naturale, equilibrio della densità e copertura frontale-centrale. Al termine è stato applicato il supporto PRP.',
		'Ricardo came to our clinic from Ireland to restore a natural hairline and improve density across the frontal area, temples and a small thinning area on the crown. Based on his consultation plan and his wish for a natural-looking result, we adjusted the frontal line to his facial structure and planned dense implantation in the front, with additional grafts placed in the temples and crown for overall balance. The procedure was performed with the DHI Vita technique in a single session, transplanting approximately 4,200 grafts. The grafts were extracted with good hair quality, then implanted with attention to natural direction, symmetry, density balance and frontal-to-crown coverage. The operation progressed normally, with PRP support at the end.' => 'Ricardo è arrivato dall’Irlanda per ripristinare un’attaccatura naturale e aumentare la densità nella zona frontale, nelle tempie e in una piccola area diradata della corona. In base al piano e al desiderio di un risultato naturale, abbiamo adattato la linea frontale alla struttura del viso, pianificando un impianto denso davanti e innesti aggiuntivi nelle tempie e nella corona. La tecnica DHI Vita è stata eseguita in un’unica seduta con circa 4.200 innesti, impiantati rispettando direzione naturale, simmetria, equilibrio della densità e copertura dalla zona frontale alla corona. L’intervento si è concluso regolarmente con supporto PRP.',
		'Sam came to our clinic from Ireland to improve his hairline and increase overall density across the frontal area, mid-scalp and crown. Based on his consultation plan and his wish for full coverage in a single session, we planned maximum graft extraction and focused on building good density in the frontal hairline first, then distributed the remaining grafts through the mid-scalp and crown for balanced coverage. The procedure was performed with the FUE Vita technique in a single session, transplanting 6,200 grafts in total. Grafts were extracted homogeneously from the donor area with good quality, then implanted with attention to natural direction, density balance and overall coverage. The operation progressed normally, with PRP support at the end.' => 'Sam è arrivato dall’Irlanda per migliorare l’attaccatura e aumentare la densità complessiva nella zona frontale, centrale e nella corona. In base al piano e al desiderio di una copertura completa in un’unica seduta, abbiamo programmato il massimo prelievo possibile, dando priorità alla densità dell’attaccatura e distribuendo poi gli innesti rimanenti nella zona centrale e nella corona. La tecnica FUE Vita è stata eseguita in un’unica seduta con 6.200 innesti. Gli innesti, di buona qualità, sono stati prelevati in modo omogeneo e impiantati rispettando direzione naturale, equilibrio della densità e copertura complessiva. L’intervento si è concluso regolarmente con supporto PRP.',

		// Signature-card long descriptions.
		'Our patented Exosome Treatment is derived from mesenchymal stem cells found in the umbilical cord — designed to lift hair-follicle survival to 98% over 72 hours, with faster recovery, stronger growth, and naturally lasting results.' => 'Il nostro trattamento Exosome brevettato deriva da cellule staminali mesenchimali presenti nel cordone ombelicale ed è progettato per portare la sopravvivenza dei follicoli fino al 98% oltre le 72 ore, favorendo recupero più rapido, crescita più forte e risultati naturali e duraturi.',
		'TrichoLab examines your hair and scalp with millimetric accuracy — measuring follicle density, thickness, donor capacity, and loss patterns — so every graft is planned for your unique anatomy and the result feels naturally yours.' => 'TrichoLab esamina capelli e cuoio capelluto con precisione millimetrica, misurando densità follicolare, spessore, capacità donatrice e schema di caduta, affinché ogni innesto sia pianificato in base alla tua anatomia e il risultato appaia naturalmente tuo.',
		'Grafts lose strength the moment they leave the body. Our VITA Protocol bathes them in a specially formulated vitamin cocktail with cool-vapor application — keeping every follicle alive, nourished, and resilient until placement.' => 'Gli innesti iniziano a perdere vitalità appena vengono prelevati. Il protocollo VITA li mantiene in una soluzione vitaminica appositamente formulata con applicazione a vapore freddo, conservando ogni follicolo vitale, nutrito e resistente fino all’impianto.',
		// Floating WhatsApp button + fake WhatsApp chat popup.
		'WhatsApp chat' => 'Chat WhatsApp',
		'Close chat' => 'Chiudi la chat',
		'online' => 'online',
		'Today' => 'Oggi',
		'Hi! 👋 Welcome to Estecapelli. Tell us which treatment you are interested in and we will get back to you within minutes.' => 'Ciao! 👋 Benvenuto in Estecapelli. Dicci quale trattamento ti interessa e ti risponderemo in pochi minuti.',
		'Type a message' => 'Scrivi un messaggio',
		'Write your message first' => 'Scrivi prima il tuo messaggio',
		'Send' => 'Invia',
		'Confirm your message' => 'Conferma il tuo messaggio',
		'This message will be sent to our WhatsApp:' => 'Questo messaggio sarà inviato al nostro WhatsApp:',
		'Cancel' => 'Annulla',
		// 404 page.
		'This page could not be found' => 'Questa pagina non è stata trovata',
		'The page you are looking for may have been moved or no longer exists. You can head back to the homepage, or pick one of the sections below.' => 'La pagina che stai cercando potrebbe essere stata spostata o non esistere più. Puoi tornare alla home page oppure scegliere una delle sezioni qui sotto.',
		'Back to homepage' => 'Torna alla home',
		'Contact us' => 'Contattaci',
		'Popular sections' => 'Sezioni principali',
		'Site sections' => 'Sezioni del sito',
		);
	}

	return $strings[ $text ] ?? $translation;
}

add_filter( 'ngettext', 'estecapelli_it_ngettext_fallback', 25, 5 );
/** Translate the reading-time label used by Blog without changing articles. */
function estecapelli_it_ngettext_fallback( $translation, $single, $plural, $number, $domain ) {
	if (
		'estecapelli' === $domain &&
		estecapelli_is_italian_request() &&
		in_array( $translation, array( $single, $plural ), true )
	) {
		if ( '%d min read' === $single && '%d min read' === $plural ) {
			return '%d min di lettura';
		}
		if ( '%d star' === $single && '%d stars' === $plural ) {
			return 1 === (int) $number ? '%d stella' : '%d stelle';
		}
	}

	return $translation;
}
