<?php
/**
 * Romanian fallbacks for front-end theme strings.
 *
 * WPML String Translation remains authoritative. These values only fill text
 * that is still identical to its English source, which is every string while
 * Romanian is a freshly added language and its .po files are still empty.
 *
 * Register is informal singular ("tu"), matching the other languages and the
 * Romanian handoff spec. Medical claims are kept exactly as strong, or as
 * hedged, as the English source.
 *
 * @package Estecapelli
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/** Whether the current request is the indexed Romanian language. */
function estecapelli_is_romanian_request() {
	// The URL is the contract and is checked first: WPML answers with the
	// site's DEFAULT language wherever it cannot resolve a request — most
	// visibly on a 404 — which would render the Romanian error page in
	// English. This is the same trap /pt/ fell into.
	if ( function_exists( 'estecapelli_request_language_code' ) ) {
		$requested = estecapelli_request_language_code();
		if ( '' !== $requested ) {
			return 'ro' === $requested;
		}
	}

	$language = (string) apply_filters( 'wpml_current_language', null );
	if ( function_exists( 'estecapelli_indexed_language_code' ) ) {
		return 'ro' === estecapelli_indexed_language_code( $language );
	}

	return 'ro' === strtolower( str_replace( '_', '-', $language ) );
}

add_filter( 'gettext', 'estecapelli_ro_gettext_fallback', 25, 3 );
/** Supply Romanian only when no earlier translation provider changed text. */
function estecapelli_ro_gettext_fallback( $translation, $text, $domain ) {
	if ( 'estecapelli' !== $domain || $translation !== $text || ! estecapelli_is_romanian_request() ) {
		return $translation;
	}

	static $strings = null;
	if ( null === $strings ) {
		$strings = array(
			// Journal / blog UI.
			'From the Journal' => 'De pe blogul nostru',
			'Research, results & recovery' => 'Cercetare, rezultate și recuperare',
			'Expert articles on hair restoration, plastic surgery, dental treatment and the journey to your transformation — written by the Estecapelli team.' => 'Articole de specialitate despre restaurarea părului, chirurgie plastică, tratamente dentare și drumul către transformarea ta — scrise de echipa Estecapelli.',
			'Article categories' => 'Categorii de articole',
			'All' => 'Toate',
			'Latest article' => 'Cel mai recent articol',
			'Read the article' => 'Citește articolul',
			'Keep reading' => 'Continuă lectura',
			'Articles from the Estecapelli journal.' => 'Articole din jurnalul Estecapelli.',
			'All articles' => 'Toate articolele',
			'Share' => 'Distribuie',
			'Share on Facebook' => 'Distribuie pe Facebook',
			'Share on WhatsApp' => 'Distribuie pe WhatsApp',
			'Copy link' => 'Copiază linkul',
			'Pages:' => 'Pagini:',
			'Read more' => 'Citește mai mult',
			'Posts pagination' => 'Paginarea articolelor',
			'Newer' => 'Mai noi',
			'Older' => 'Mai vechi',
			'No articles found here yet.' => 'Încă nu au fost găsite articole aici.',
			'No articles have been published yet. New posts will appear here as soon as our team publishes them.' => 'Încă nu a fost publicat niciun articol. Articolele noi vor apărea aici imediat ce echipa noastră le publică.',

			// Shared navigation, footer and lead forms.
			'Skip to content' => 'Sari la conținut',
			'Primary' => 'Navigare principală',
			'Toggle menu' => 'Deschide sau închide meniul',
			'Choose language. Current language: %s' => 'Alege limba. Limba curentă: %s',
			'Free Consultation' => 'Consultație gratuită',
			'Book a consultation' => 'Programează o consultație',
			'Ready to start your transformation?' => 'Ești gata să îți începi transformarea?',
			'Speak with our medical team — free, no obligation. Get a personalized plan based on your goals.' => 'Vorbește cu echipa noastră medicală — gratuit și fără nicio obligație. Primești un plan personalizat, în funcție de obiectivele tale.',
			'Get a Free Consultation' => 'Solicită o consultație gratuită',
			'Chat on WhatsApp' => 'Scrie-ne pe WhatsApp',
			// WhatsApp hand-off notice.
			'Please leave the message already prepared in WhatsApp exactly as it is — it tells our team which page you are writing from, so we can reply to you faster. You are very welcome to add your question right after it.' => 'Te rugăm să lași exact așa cum este mesajul deja pregătit în WhatsApp — el îi spune echipei noastre de pe ce pagină ne scrii, ca să îți putem răspunde mai repede. Poți adăuga liniștit întrebarea ta imediat după el.',
			'Continue to WhatsApp' => 'Continuă pe WhatsApp',
			'Here are my photos:' => 'Acestea sunt fotografiile mele:',
			'Our Licences' => 'Certificările noastre',
			'Sitemap' => 'Harta site-ului',
			'Language' => 'Limbă',
			'Get a free consultation — leave your details and we will reach out.' => 'Primește o consultație gratuită — lasă-ne datele tale și te contactăm noi.',
			'Name and surname' => 'Nume și prenume',
			'Phone number' => 'Număr de telefon',
			'Email address' => 'Adresă de e-mail',
			'Request Call Back' => 'Cere să fii sunat',
			'All rights reserved.' => 'Toate drepturile rezervate.',
			'Footer legal' => 'Linkuri legale din subsol',
			'Privacy Policy' => 'Politica de confidențialitate',
			'Terms' => 'Termeni și condiții',
			'Cookie Policy' => 'Politica de cookie-uri',
			'KVKK Notice' => 'Notificare KVKK',
			'Free Hair Analysis' => 'Analiză gratuită a părului',
			'Reply in 2 minutes' => 'Răspuns în 2 minute',
			'Photo viewer' => 'Vizualizator de fotografii',
			'Close' => 'Închide',
			'Previous photo' => 'Fotografia anterioară',
			'Next photo' => 'Fotografia următoare',
			'Book your free consultation' => 'Programează-ți consultația gratuită',
			'Leave your details and a medical consultant will get back to you shortly — no obligation.' => 'Lasă-ne datele tale și un consultant medical te va contacta în scurt timp — fără nicio obligație.',
			'Full name' => 'Nume complet',
			'Phone' => 'Telefon',
			'Email' => 'E-mail',
			'Note' => 'Observații',
			'Tell us about your goals, or any questions you have…' => 'Spune-ne care sunt obiectivele tale sau ce întrebări ai…',
			'Request a Free Consultation' => 'Solicită o consultație gratuită',
			'Thank you! Your request has been received — our team will contact you shortly.' => 'Îți mulțumim! Am primit solicitarea ta — echipa noastră te va contacta în scurt timp.',
			'Hello Estecapelli, I would like to book a free consultation.' => 'Bună ziua, Estecapelli, aș dori să programez o consultație gratuită.',

			// Contact and reusable form copy.
			'Hello Estecapelli, I would like a free analysis. Here are my photos:' => 'Bună ziua, Estecapelli, aș dori o analiză gratuită. Acestea sunt fotografiile mele:',
			'English' => 'Engleză',
			'French' => 'Franceză',
			'Italian' => 'Italiană',
			'Spanish' => 'Spaniolă',
			'Polish' => 'Poloneză',
			'Portuguese' => 'Portugheză',
			'Romanian' => 'Română',
			'Turkish' => 'Turcă',
			'Contact Us' => 'Contactează-ne',
			'Let’s start your journey' => 'Să începem drumul tău',
			'Reach our team by WhatsApp, phone or email — or leave your details and a medical consultant will get back to you in your own language.' => 'Contactează echipa noastră pe WhatsApp, telefonic sau prin e-mail — sau lasă-ne datele tale și un consultant medical îți va răspunde în limba ta.',
			'We usually reply within an hour' => 'De obicei răspundem în mai puțin de o oră',
			'Chat with us now' => 'Scrie-ne acum',
			'Call' => 'Sună',
			'Request a free consultation' => 'Solicită o consultație gratuită',
			'Tell us a little about you and we’ll be in touch shortly.' => 'Spune-ne câteva cuvinte despre tine și te contactăm în scurt timp.',
			'Interested in' => 'Tratament de interes',
			'Select a treatment' => 'Alege un tratament',
			'Hair Transplant' => 'Transplant de păr',
			'Plastic Surgery' => 'Chirurgie plastică',
			'Dental Treatment' => 'Tratament dentar',
			'Not sure yet' => 'Încă nu m-am hotărât',
			'Message' => 'Mesaj',
			'Send Request' => 'Trimite solicitarea',
			'Please enter a valid phone number.' => 'Te rugăm să introduci un număr de telefon valid.',
			'Please enter a valid email address.' => 'Te rugăm să introduci o adresă de e-mail validă.',
			'Please enter your name.' => 'Te rugăm să introduci numele tău.',
			'Name is required.' => 'Numele este obligatoriu.',
			'Please enter your phone number.' => 'Te rugăm să introduci numărul tău de telefon.',
			'Please complete the security check and try again.' => 'Te rugăm să finalizezi verificarea de securitate și să încerci din nou.',
			'The security check is temporarily unavailable. Please try again.' => 'Verificarea de securitate este temporar indisponibilă. Te rugăm să încerci din nou.',
			'Please refresh the page and submit the form again.' => 'Te rugăm să reîmprospătezi pagina și să trimiți din nou formularul.',
			'Too many requests. Please wait a few minutes and try again.' => 'Prea multe solicitări. Te rugăm să aștepți câteva minute și să încerci din nou.',
			'Please select a valid country code.' => 'Te rugăm să alegi un prefix de țară valid.',
			'This number is too short for the selected country.' => 'Acest număr este prea scurt pentru țara selectată.',
			'This number is too long for the selected country.' => 'Acest număr este prea lung pentru țara selectată.',
			'Please enter the full phone number, including the area code.' => 'Te rugăm să introduci numărul de telefon complet, inclusiv prefixul.',
			'Please enter a valid phone number for the selected country.' => 'Te rugăm să introduci un număr de telefon valid pentru țara selectată.',
			'Visit & reach us' => 'Vizitează-ne sau contactează-ne',
			'Address' => 'Adresă',
			'Working hours' => 'Program de lucru',
			'Monday – Sunday: 09:00 – 18:00 (GMT+3)' => 'Luni – duminică: 09:00 – 18:00 (GMT+3)',
			'What happens next?' => 'Ce se întâmplă mai departe?',
			'We review your request and reach out to understand your goals.' => 'Analizăm solicitarea ta și te contactăm pentru a înțelege ce îți dorești.',
			'You receive a free, personalised treatment plan and quote.' => 'Primești gratuit un plan de tratament personalizat și o ofertă de preț.',
			'We arrange your dates, travel and stay — and welcome you to Istanbul.' => 'Îți organizăm datele, călătoria și cazarea — și te primim la Istanbul.',
			'Send your photos, get a free analysis' => 'Trimite-ne fotografiile și primești o analiză gratuită',
			'Share a few photos of your hair, face or smile and our specialists will assess your case and recommend the right approach — at no cost and with no obligation.' => 'Trimite câteva fotografii ale părului, feței sau zâmbetului tău, iar specialiștii noștri îți vor evalua cazul și îți vor recomanda abordarea potrivită — gratuit și fără nicio obligație.',
			'Send Photos on WhatsApp' => 'Trimite fotografiile pe WhatsApp',
			'Talk to us in your own language' => 'Vorbește cu noi în limba ta',
			'Estecapelli clinic location' => 'Locația clinicii Estecapelli',

			// Before/After, doctor pages and treatment controls.
			'Before' => 'Înainte',
			'After' => 'După',
			'Before & After' => 'Înainte și după',
			'Before treatment' => 'Înainte de tratament',
			'After treatment' => 'După tratament',
			'%s grafts' => '%s grefe',
			'Before and after results' => 'Rezultate înainte și după',
			'Real Results' => 'Rezultate reale',
			'Before &amp; After' => 'Înainte și după',
			'Outcomes from our %s patients.' => 'Rezultatele pacienților noștri din %s.',
			'Previous result' => 'Rezultatul anterior',
			'Next result' => 'Rezultatul următor',
			'Results will appear here soon.' => 'Rezultatele vor apărea aici în curând.',
			'Treatment categories' => 'Categorii de tratamente',
			'%s services' => 'Servicii de %s',
			'View treatment' => 'Vezi tratamentul',
			'Enlarge result' => 'Mărește rezultatul',
			'Before and after result' => 'Rezultat înainte și după',
			'grafts' => 'grefe',
			'See full gallery' => 'Vezi galeria completă',
			'Résumé' => 'CV',
			'Book a Free Consultation' => 'Programează o consultație gratuită',
			'View Résumé' => 'Vezi CV-ul',
			'Meet the doctor' => 'Cunoaște medicul',
			'Languages spoken' => 'Limbi vorbite',
			'Procedure quick facts' => 'Informații esențiale despre procedură',
			'Get Started' => 'Începe acum',
			'Learn More' => 'Află mai multe',
			'Learn more' => 'Află mai multe',
			'Previous slide' => 'Slide-ul anterior',
			'Next slide' => 'Slide-ul următor',
			'Choose slide' => 'Alege slide-ul',
			'Slide %d' => 'Slide-ul %d',
			'Next step' => 'Pasul următor',
			'Previous step' => 'Pasul anterior',
			'Steps' => 'Pași',
			'step' => 'pas',
			'Procedure details' => 'Detalii despre procedură',

			// Homepage hero and service discovery.
			'Highlights' => 'Pe scurt',
			'Signature Methods' => 'Metode exclusive',
			'Select a method to play' => 'Alege o metodă pentru redare',
			'World-Class Experience' => 'Experiență de nivel mondial',
			'Estecapelli patient result' => 'Rezultatul unui pacient Estecapelli',
			'Previous patient' => 'Pacientul anterior',
			'Next patient' => 'Pacientul următor',
			'Estecapelli Dental' => 'Estecapelli Dental',
			'Estecapelli dental patient smiling' => 'Pacient Estecapelli Dental zâmbind',
			'A Smile Designed Around You' => 'Un zâmbet creat pentru tine',
			'Hollywood smiles, veneers and full-mouth restorations — crafted by our specialists for a natural, confident result that lasts.' => 'Zâmbete de Hollywood, fațete și reabilitări dentare complete — realizate de specialiștii noștri pentru un rezultat natural, sigur și de durată.',
			'Hollywood Smile & porcelain veneers' => 'Zâmbet de Hollywood și fațete din porțelan',
			'Implants & full-mouth restoration' => 'Implanturi și reabilitare dentară completă',
			'One trusted clinic, all-inclusive care' => 'O singură clinică de încredere, îngrijire all-inclusive',
			'Explore Dental Treatments' => 'Descoperă tratamentele dentare',
			'OUR SIGNATURE METHODS' => 'METODELE NOASTRE EXCLUSIVE',
			'Two techniques. Registered to our name.' => 'Două tehnici. Înregistrate pe numele nostru.',
			'Two exclusive, trademarked protocols — developed in-house.' => 'Două protocoale exclusive, înregistrate ca marcă — dezvoltate în clinica noastră.',
			'Treatment' => 'Tratament',
			'Explore VITA®' => 'Descoperă VITA®',
			'Explore Exosome®' => 'Descoperă Exosome®',
			'EST. 2010 · ISTANBUL' => 'DIN 2010 · ISTANBUL',
			'EST. 2010 · ISTANBUL, TÜRKİYE' => 'DIN 2010 · ISTANBUL, TURCIA',
			'One of the World’s Most Experienced Hair Restoration Teams' => 'Una dintre cele mai experimentate echipe de restaurare a părului din lume',
			'Join the thousands who have come to Estecapelli to regain their confidence.' => 'Alătură-te miilor de pacienți care au ales Estecapelli pentru a-și recăpăta încrederea.',
			'Schedule a Free Consultation' => 'Programează o consultație gratuită',
			'Over 50,000+' => 'Peste 50.000',
			'5-Star Results' => 'Rezultate de 5 stele',
			'Actual Estecapelli patient. Individual results may vary.' => 'Pacient real Estecapelli. Rezultatele pot varia de la o persoană la alta.',
			'FIFTEEN YEARS' => 'CINCISPREZECE ANI',
			'FOR WOMEN · DISCREET & NATURAL' => 'PENTRU FEMEI · DISCRET ȘI NATURAL',
			'Women’s Hair Transplant in Istanbul' => 'Transplant de păr pentru femei, la Istanbul',
			'Thinning along the parting, a receding hairline or overall loss of density affects women too. Our female-focused approach restores fullness with unshaven techniques, complete privacy and natural, permanent results.' => 'Rărirea părului de-a lungul cărării, retragerea liniei frontale a părului sau pierderea generală de densitate afectează și femeile. Abordarea noastră dedicată femeilor redă volumul prin tehnici fără bărbierire, cu intimitate deplină și rezultate naturale și permanente.',
			'Unshaven, discreet techniques' => 'Tehnici discrete, fără bărbierire',
			'Natural hairline & density design' => 'Proiectarea naturală a liniei frontale și a densității',
			'Female patient privacy at every step' => 'Intimitatea pacientelor la fiecare pas',
			'Years of Experience' => 'Ani de experiență',
			'Happy Patients' => 'Pacienți mulțumiți',
			'Countries Served' => 'Țări deservite',
			'Support Team' => 'Echipă de asistență',
			'What We Treat' => 'Ce tratăm',
			'Pick a field. See our signature treatments.' => 'Alege un domeniu. Descoperă tratamentele noastre de referință.',
			'Switch between tabs to explore the methods we are best known for in each field of care.' => 'Schimbă între file pentru a descoperi metodele pentru care suntem cel mai bine cunoscuți în fiecare domeniu de îngrijire.',
			'Previous treatments' => 'Tratamentele anterioare',
			'Next treatments' => 'Tratamentele următoare',

			// Homepage supporting sections.
			'The Comparison' => 'Comparația',
			'Global standards, Turkish expertise.' => 'Standarde internaționale, experiență turcească.',
			'See how our comprehensive approach and advanced techniques set us apart from other clinics.' => 'Vezi cum abordarea noastră completă și tehnicile avansate ne diferențiază de alte clinici.',
			'Built for patients who refuse to compromise.' => 'Gândit pentru pacienții care nu acceptă compromisuri.',
			'At Estecapelli, we go beyond expectations to deliver personalised, high-quality care backed by years of experience and international standards. Our expert team combines innovative methods with a patient-first approach to deliver results that look natural and feel confident.' => 'La Estecapelli depășim așteptările și oferim îngrijire personalizată, de înaltă calitate, susținută de ani de experiență și de standarde internaționale. Echipa noastră de specialiști combină metode inovatoare cu o abordare centrată pe pacient, pentru rezultate care arată natural și îți dau încredere.',
			'Experience the Estecapelli difference — advanced techniques, patient-focused care.' => 'Descoperă diferența Estecapelli — tehnici avansate și îngrijire centrată pe pacient.',
			'Other Clinics' => 'Alte clinici',
			'Premium Care' => 'Îngrijire premium',
			'Standard Care' => 'Îngrijire standard',
			'5-Star Hotel Accommodation' => 'Cazare la hotel de 5 stele',
			'VIP Transfer Service' => 'Serviciu de transfer VIP',
			'Personal Translator' => 'Traducător personal',
			'Latest Technology Implementation' => 'Tehnologie de ultimă generație',
			'Success-Oriented Treatment Planning' => 'Planificarea tratamentului orientată spre rezultat',
			'Innovative Techniques (Exosome, FUE, DHI, VITA)' => 'Tehnici inovatoare (Exosome, FUE, DHI, VITA)',
			'Regenerative Stem Cell Therapy' => 'Terapie regenerativă cu celule stem',
			'Dedicated Post-Op Follow-Up Team' => 'Echipă dedicată de monitorizare postoperatorie',
			'Pain-Free Anaesthesia' => 'Anestezie fără durere',
			'Nine details where every choice matters.' => 'Nouă detalii în care fiecare alegere contează.',
			'Our Expertise' => 'Experiența noastră',
			'Three methods that shape every treatment.' => 'Trei metode care stau la baza fiecărui tratament.',
			'Two are exclusively ours. One sets the standard for personalised planning. All three power the results our patients trust us for.' => 'Două sunt exclusiv ale noastre. Una stabilește standardul planificării personalizate. Toate trei susțin rezultatele pentru care pacienții au încredere în noi.',
			'Patented · Estecapelli Exclusive' => 'Brevetat · Exclusiv Estecapelli',
			'Premium Hair Transplant Method' => 'Metodă premium de transplant de păr',
			'Mesenchymal stem-cell support that keeps follicles alive longer.' => 'Suport cu celule stem mezenchimale care menține foliculii vii mai mult timp.',
			'Follicle survival over 72 hours' => 'Supraviețuirea foliculilor peste 72 de ore',
			'Learn about Exosome FUE' => 'Află despre Exosome FUE',
			'AI-Powered Diagnosis' => 'Diagnostic asistat de inteligență artificială',
			'Millimetric Hair & Scalp Analysis' => 'Analiză milimetrică a părului și a scalpului',
			'AI maps your scalp before a single graft is planned.' => 'Inteligența artificială îți cartografiază scalpul înainte să fie planificată o singură grefă.',
			'Millimetric' => 'Milimetric',
			'Precision per scalp scan' => 'Precizie la fiecare scanare a scalpului',
			'Learn more about TrichoLab' => 'Află mai multe despre TrichoLab',
			'Signature Protocol · Estecapelli Exclusive' => 'Protocol exclusiv · Exclusiv Estecapelli',
			'Power Derived from Vitamins' => 'Puterea vitaminelor',
			'A vitamin-cooled bath that keeps grafts strong out of the body.' => 'O baie vitaminizată și răcită care menține grefele puternice în afara corpului.',
			'Cool-Vapor' => 'Vapori reci',
			'Vitamin-nourished grafts' => 'Grefe hrănite cu vitamine',
			'Learn more about VITA' => 'Află mai multe despre VITA',
			'Real Stories' => 'Povești reale',
			'Their results speak louder than any ad ever could.' => 'Rezultatele lor vorbesc mai tare decât ar putea-o face vreodată o reclamă.',
			'Patient from' => 'Pacient din',
			'More patient stories' => 'Mai multe povești ale pacienților',
			'On the playlist' => 'În playlist',
			'Our Clinic' => 'Clinica noastră',
			'Step inside our Istanbul clinic' => 'Pășește în clinica noastră din Istanbul',
			'A Ministry-of-Health licensed, hospital-grade facility in the heart of Istanbul — modern operation rooms, sterile theatres and a permanent on-site medical team.' => 'O unitate de nivel spitalicesc, autorizată de Ministerul Sănătății, în inima Istanbulului — săli de operație moderne, spații sterile și o echipă medicală permanentă la fața locului.',
			'Clinic walkthrough' => 'Tur al clinicii',
			'Hair Transplant Surgery Room' => 'Sala de operație pentru transplantul de păr',
			'TrichoLab Room' => 'Sala TrichoLab',
			'Lobby' => 'Recepție',
			'Dental Clinic' => 'Clinica dentară',
			'Our partner hotels' => 'Hotelurile noastre partenere',
			'Hair Analysis Lab' => 'Laboratorul de analiză a părului',
			'Your Personalised Hair Plan, Powered by Estecapelli' => 'Planul tău personalizat pentru păr, creat de Estecapelli',
			'I know my hair-loss area' => 'Știu care este zona mea afectată de căderea părului',
			'Start self-assessment' => 'Începe autoevaluarea',
			'Analyse my photos with AI' => 'Analizează-mi fotografiile cu inteligența artificială',
			'Start AI Analysis' => 'Începe analiza AI',
			'Back to options' => 'Înapoi la opțiuni',
			'Tap the areas where you are losing hair' => 'Atinge zonele în care îți cade părul',
			'Selected areas' => 'Zone selectate',
			'No area selected yet.' => 'Nu ai selectat încă nicio zonă.',
			'Your name' => 'Numele tău',
			'Phone / WhatsApp' => 'Telefon / WhatsApp',
			'Your number' => 'Numărul tău',
			'Your email' => 'E-mailul tău',
			'Get my analysis' => 'Vreau analiza mea',
			'Real Patients · Real Results' => 'Pacienți reali · Rezultate reale',
			'Choose a hair-transplant technique to browse real patient results.' => 'Alege o tehnică de transplant de păr pentru a vedea rezultate reale ale pacienților.',
			'Hair transplant techniques' => 'Tehnici de transplant de păr',
			'View all results' => 'Vezi toate rezultatele',

			// Shared controls, accessibility and utility labels.
			'%1$s grafts · %2$s' => '%1$s grefe · %2$s',
			'Close video' => 'Închide videoclipul',
			'Back to gallery' => 'Înapoi la galerie',
			'Click any photo to open the gallery' => 'Dă clic pe orice fotografie pentru a deschide galeria',
			'Contents' => 'Cuprins',
			'Enlarge photo' => 'Mărește fotografia',
			'Go to photo %d' => 'Mergi la fotografia %d',
			'Hover or tap to discover' => 'Treci cu mouse-ul sau atinge pentru a descoperi',
			'Included' => 'Inclus',
			'Included at Estecapelli' => 'Inclus la Estecapelli',
			'Not included' => 'Nu este inclus',
			'Open gallery: %s' => 'Deschide galeria: %s',
			'Open the gallery' => 'Deschide galeria',
			'Play %s video' => 'Redă videoclipul %s',
			'Play %s — %s' => 'Redă %s — %s',
			'Rated %d out of 5' => 'Evaluare: %d din 5',
			'Scalp zones' => 'Zonele scalpului',
			'Scroll left' => 'Derulează la stânga',
			'Scroll right' => 'Derulează la dreapta',
			'Treatments' => 'Tratamente',
			'Trustpilot rating: 5 out of 5, Excellent' => 'Evaluare Trustpilot: 5 din 5, Excelent',
			'Use the arrows to browse · click any photo to enlarge' => 'Folosește săgețile pentru a naviga · dă clic pe o fotografie pentru a o mări',
			'View result %d' => 'Vezi rezultatul %d',
			'Excellent' => 'Excelent',
			'on Trustpilot' => 'pe Trustpilot',
			'Google Reviews' => 'Recenzii Google',
			'Estecapelli in numbers' => 'Estecapelli în cifre',
			'Patients trust us by the numbers' => 'Încrederea pacienților noștri, în cifre',
			'Estecapelli versus other clinics — feature comparison' => 'Estecapelli față de alte clinici — comparație de servicii',
			'Internationally Accredited & Certified' => 'Acreditați și certificați internațional',
			'Internationally accredited & certified — Ministry of Health, Certified Medical Travel Agency, HRSA, NACo Award, ISO 13485' => 'Acreditați și certificați internațional — Ministerul Sănătății, agenție certificată de turism medical, HRSA, premiul NACo, ISO 13485',
			'Internationally accredited — Ministry of Health, HRSA, NACo, ISO 13485, Certified Medical Travel Agency' => 'Acreditare internațională — Ministerul Sănătății, HRSA, NACo, ISO 13485, agenție certificată de turism medical',
			'Internationally accredited — Ministry of Health, HRSA, NACo, ISO 13485, Certified Medical Travel Agent' => 'Acreditare internațională — Ministerul Sănătății, HRSA, NACo, ISO 13485, agent certificat de turism medical',

			// About flyout and treatment cards.
			'Aesthetic Excellence, Backed by Medical Trust.' => 'Excelență estetică, susținută de încredere medicală.',
			"From hair restoration to plastic, dental and non-surgical aesthetics — Estecapelli's board-certified doctors deliver hospital-grade care with the precision your transformation deserves." => 'De la restaurarea părului la chirurgie plastică, tratamente dentare și estetică non-chirurgicală — medicii specialiști ai Estecapelli oferă îngrijire de nivel spitalicesc, cu precizia pe care transformarea ta o merită.',
			'Dr. Mehmet Hanifi Kutlar' => 'Dr. Mehmet Hanifi Kutlar',
			'Medical Director & Co-founder' => 'Medic-șef și cofondator',
			'15+ years in aesthetic medicine' => 'Peste 15 ani în medicina estetică',
			'ACCREDITED CLINIC' => 'CLINICĂ ACREDITATĂ',
			'Ministry of Health Licensed' => 'Autorizată de Ministerul Sănătății',
			'ISO 9001 · TURSAB Certified' => 'Certificată ISO 9001 · TURSAB',
			'About Estecapelli' => 'Despre Estecapelli',
			'About Us' => 'Despre noi',
			'Who we are and what drives our clinic forward.' => 'Cine suntem și ce ne împinge clinica înainte.',
			'Our Doctors' => 'Medicii noștri',
			'Meet the surgeons leading every procedure.' => 'Cunoaște chirurgii care conduc fiecare procedură.',
			'Our Team' => 'Echipa noastră',
			'The full medical and patient-care team behind your treatment.' => 'Întreaga echipă medicală și de îngrijire a pacienților din spatele tratamentului tău.',
			'Visit Us' => 'Vizitează-ne',
			'Medical Treatment' => 'Tratament medical',
			'Hair Transplant Care & Technology' => 'Îngrijire și tehnologie pentru transplantul de păr',
			'Micro Sapphire FUE' => 'Micro Sapphire FUE',
			'Sapphire FUE Hair Transplant' => 'Transplant de păr Sapphire FUE',
			'Sapphire-blade precision for natural density and faster healing.' => 'Precizia lamelor de safir pentru densitate naturală și vindecare mai rapidă.',
			'A natural and permanent hair transplant technique where follicles are placed via sapphire blades.' => 'O tehnică naturală și permanentă de transplant de păr, în care foliculii sunt implantați cu lame de safir.',
			'DHI Hair Transplant' => 'Transplant de păr DHI',
			'A modern hair transplantation method performed with a Choi pen that allows precise placement.' => 'O metodă modernă de transplant de păr, realizată cu stiloul Choi, care permite o implantare precisă.',
			'Choi-pen implantation for precise angle and direction control.' => 'Implantare cu stiloul Choi, pentru un control precis al unghiului și al direcției.',
			'Exosome FUE Hair Transplant' => 'Transplant de păr Exosome FUE',
			'Exosome Treatment' => 'Tratamentul Exosome',
			'Cell-regenerating exosomes that keep follicles alive longer.' => 'Exozomi care regenerează celulele și mențin foliculii vii mai mult timp.',
			'Supported by cell-regenerating exosomes, it keeps hair follicles alive for longer-lasting density.' => 'Susținut de exozomi care regenerează celulele, menține foliculii de păr vii pentru o densitate de mai lungă durată.',
			'VITA Treatment' => 'Tratamentul VITA',
			"Estecapelli's signature protocol that revitalises scalp & strands." => 'Protocolul exclusiv Estecapelli care revitalizează scalpul și firele de păr.',
			"Estecapelli's signature method that revitalizes the scalp and strengthens hair." => 'Metoda exclusivă Estecapelli care revitalizează scalpul și întărește părul.',
			'POPULAR' => 'POPULAR',
			'SIGNATURE' => 'EXCLUSIV',
			'Rhinoplasty' => 'Rinoplastie',
			'Nose reshaping that refines proportions and function.' => 'Remodelarea nasului, care îmbunătățește proporțiile și funcția.',
			'Nose reshaping surgery that refines proportions and function.' => 'Intervenție de remodelare a nasului, care îmbunătățește proporțiile și funcția.',
			'BBL (Brazilian Butt Lift)' => 'BBL (Brazilian Butt Lift)',
			'Brazilian Butt Lift — natural contouring with fat transfer.' => 'Brazilian Butt Lift — conturare naturală prin transfer de grăsime.',
			'Natural body contouring with fat transfer to the buttocks.' => 'Conturare naturală a corpului prin transfer de grăsime în zona feselor.',
			'Facelift' => 'Lifting facial',
			'Face & Neck Lift Surgery' => 'Lifting facial și de gât',
			'Restores facial contour and reduces visible signs of aging.' => 'Reface conturul feței și reduce semnele vizibile ale îmbătrânirii.',
			'Breast Aesthetics' => 'Estetica sânilor',
			'Augmentation, lift and reduction tailored to your goals.' => 'Mărire, ridicare și reducere, adaptate obiectivelor tale.',
			'Augmentation, lift, and reduction tailored to your goals.' => 'Mărire, ridicare și reducere, adaptate obiectivelor tale.',
			'Abdominoplasty (Tummy Tuck)' => 'Abdominoplastie',
			'Flattens and tightens the abdomen for a smoother profile.' => 'Aplatizează și tonifiază abdomenul pentru un profil mai armonios.',
			'Liposuction' => 'Liposucție',
			'Removes localized fat deposits to reshape the body.' => 'Elimină depozitele de grăsime localizată pentru a remodela corpul.',
			'Gynecomastia' => 'Ginecomastie',
			'Surgical treatment of enlarged male breast tissue.' => 'Tratamentul chirurgical al țesutului mamar mărit la bărbați.',
			'Obesity Surgeries (Bariatric)' => 'Operații de obezitate (bariatrice)',
			'Bariatric surgery and gastric balloon for sustainable weight loss.' => 'Chirurgie bariatrică și balon gastric pentru o scădere în greutate de durată.',
			'Dental Implant' => 'Implant dentar',
			'Dental Implants' => 'Implanturi dentare',
			'Permanent replacement for missing teeth with titanium roots.' => 'Înlocuire permanentă a dinților lipsă, cu rădăcini din titan.',
			'Smile Design' => 'Designul zâmbetului',
			'A bespoke makeover that reshapes your entire smile.' => 'O transformare personalizată care îți remodelează întregul zâmbet.',
			'A bespoke makeover that reshapes your smile aesthetic.' => 'O transformare personalizată care îți remodelează estetica zâmbetului.',
			'Hollywood Smile' => 'Zâmbet de Hollywood',
			'Veneers' => 'Fațete dentare',
			'Thin porcelain shells for a flawless front-of-tooth finish.' => 'Lamele subțiri din porțelan pentru un aspect impecabil al feței vizibile a dintelui.',
			'Teeth Whitening' => 'Albirea dinților',
			'Professional bleaching for noticeably brighter teeth.' => 'Albire profesională pentru dinți vizibil mai albi.',
			'Female Hair Transplant' => 'Transplant de păr la femei',
			'Special for women, dense and natural-looking hair transplant without shaving.' => 'Transplant de păr fără bărbierire, special conceput pentru femei, cu un rezultat dens și natural.',
			'Eyebrow Transplant' => 'Transplant de sprâncene',
			'Eyebrow transplantation that gives a naturally curved and full eyebrow shape.' => 'Transplant care oferă sprâncenelor o formă natural arcuită și bine conturată.',
			'Beard Transplant' => 'Transplant de barbă',
			'Natural beard and mustache transplantation for sparse or non-existing growth.' => 'Transplant natural de barbă și mustață pentru zonele cu creștere rară sau inexistentă.',
			'Hair Mesotherapy' => 'Mezoterapie capilară',
			'A vitamin and mineral injection treatment that revitalizes hair follicles.' => 'Un tratament prin injecții cu vitamine și minerale care revitalizează foliculii de păr.',
			'Pre-Hair Transplant Period' => 'Perioada dinainte de transplantul de păr',
			'The preparation and analysis process before hair transplantation.' => 'Procesul de pregătire și analiză dinaintea transplantului de păr.',
			'Post-Hair Transplant Period' => 'Perioada de după transplantul de păr',
			'The post-procedure recovery and hair care period.' => 'Perioada de recuperare și de îngrijire a părului după procedură.',
			'AI Analysis by Estecapelli' => 'Analiza AI de la Estecapelli',
			'Advanced AI-powered hair analysis system that examines the hair and scalp in detail.' => 'Sistem avansat de analiză a părului, bazat pe inteligență artificială, care examinează în detaliu părul și scalpul.',
			'We have trained an AI to guide every patient to the best next step — get a first, personalised hair-loss assessment in seconds.' => 'Am antrenat o inteligență artificială care îndrumă fiecare pacient către următorul pas potrivit — primești în câteva secunde o primă evaluare personalizată a căderii părului.',
			'Skin Rejuvenation' => 'Întinerirea pielii',
			'Non-surgical protocols for firmer, brighter, healthier skin.' => 'Protocoale non-chirurgicale pentru o piele mai fermă, mai luminoasă și mai sănătoasă.',
			'Botox' => 'Botox',
			'Smooths expression lines for a refreshed, rested look.' => 'Netezește liniile de expresie pentru un aspect proaspăt și odihnit.',
			'Dermal Fillers' => 'Fillere dermice',
			'Restores volume to cheeks, jawline and under-eye areas.' => 'Redă volumul pomeților, conturului mandibular și zonei de sub ochi.',
			'PRP Treatment' => 'Tratament PRP',
			'Platelet-rich plasma therapy for skin and hair regeneration.' => 'Terapie cu plasmă îmbogățită cu trombocite pentru regenerarea pielii și a părului.',

			// Hair-analysis details and patient-story summaries.
			'We trained our AI on the results of more than 15,000 patients. Learning from their success stories, it analyses your condition and guides you to the treatment that fits you best.' => 'Am antrenat inteligența noastră artificială pe rezultatele a peste 15.000 de pacienți. Învățând din poveștile lor de succes, ea îți analizează situația și te îndrumă către tratamentul care ți se potrivește cel mai bine.',
			'Mark the areas where you are losing hair and tell us about your goals.' => 'Marchează zonele în care îți cade părul și spune-ne care sunt obiectivele tale.',
			'We take your photos and analyse your hair condition with an AI we have specially trained.' => 'Îți preluăm fotografiile și analizăm starea părului tău cu o inteligență artificială antrenată special de noi.',
			'A denser frontal hairline and a fuller crown.' => 'O linie frontală a părului mai densă și un creștet mai bogat.',
			'A natural hairline with balanced front-to-crown density.' => 'O linie frontală naturală, cu densitate echilibrată de la frunte la creștet.',
			'Frontal density extended through the mid-scalp.' => 'Densitate frontală extinsă prin zona mediană a scalpului.',
			'Frontal density extended toward the mid-scalp.' => 'Densitate frontală extinsă către zona mediană a scalpului.',
			'Full-coverage restoration in a single session.' => 'Acoperire completă într-o singură ședință.',
			'Hairline redesigned, density restored from front to crown.' => 'Linia frontală reproiectată, densitate refăcută de la frunte la creștet.',
			'Stronger density across front, mid-scalp and crown.' => 'Densitate mai mare în zona frontală, în zona mediană și la creștet.',
			'Ireland' => 'Irlanda',
			'Scotland' => 'Scoția',
			'England' => 'Anglia',
			'Canada' => 'Canada',
			'Alexandre came to our clinic from Ireland to redesign his hairline and improve density across the frontal area, mid-scalp and crown. Based on his desired hair model and donor capacity, we prioritised a natural, face-appropriate hairline first, then a balanced, homogeneous distribution through the mid-scalp and crown. The procedure was performed with the DHI Vita technique in a single session, transplanting 5,000 grafts in total — around 3,000 in the frontal area and hairline and roughly 2,000 across the mid-scalp and crown. The operation progressed normally, with PRP support applied at the end.' => 'Alexandre a venit la clinica noastră din Irlanda pentru a-și reproiecta linia frontală a părului și a îmbunătăți densitatea în zona frontală, în zona mediană și la creștet. În funcție de modelul de păr dorit și de capacitatea zonei donatoare, am acordat prioritate mai întâi unei linii frontale naturale, potrivite feței, iar apoi unei distribuții echilibrate și omogene prin zona mediană și creștet. Procedura a fost realizată cu tehnica DHI Vita într-o singură ședință, cu un total de 5.000 de grefe transplantate — aproximativ 3.000 în zona frontală și pe linia frontală și circa 2.000 în zona mediană și la creștet. Operația a decurs normal, iar la final s-a aplicat suport PRP.',
			'Craig came to our clinic from Scotland to improve his hairline and increase density across the frontal area and crown. Based on his hair model and consultation plan, we prioritised a denser, more natural frontal hairline first, then a homogeneous graft distribution through the top and crown to cover the visible gaps. The procedure was performed with the FUE Vita technique in a single session, transplanting 5,400 grafts in total. Grafts were extracted evenly from the donor area with good quality, then implanted with attention to natural direction, density balance and overall coverage. The operation progressed normally, with PRP support applied at the end.' => 'Craig a venit la clinica noastră din Scoția pentru a-și îmbunătăți linia frontală a părului și a crește densitatea în zona frontală și la creștet. În funcție de modelul său de păr și de planul stabilit la consultație, am acordat prioritate mai întâi unei linii frontale mai dense și mai naturale, iar apoi unei distribuții omogene a grefelor pe partea superioară și la creștet, pentru a acoperi golurile vizibile. Procedura a fost realizată cu tehnica FUE Vita într-o singură ședință, cu un total de 5.400 de grefe transplantate. Grefele au fost recoltate uniform din zona donatoare, cu o calitate bună, apoi implantate cu atenție la direcția naturală, la echilibrul densității și la acoperirea de ansamblu. Operația a decurs normal, iar la final s-a aplicat suport PRP.',
			'Dale came to our clinic from England to increase density across the frontal area, mid-scalp and crown. Based on his consultation plan and donor capacity, we focused on building stronger density in the front and crown first, while balancing the mid-scalp for an even result. The procedure was performed with the Vita protocol in a single session, transplanting 4,500 grafts in total. With a good-density donor area, the grafts were distributed to the planned coverage needs — higher density prioritised in the frontal area and crown, and the mid-scalp reinforced for a more homogeneous overall look. PRP support was applied at the end of the procedure.' => 'Dale a venit la clinica noastră din Anglia pentru a crește densitatea în zona frontală, în zona mediană și la creștet. În funcție de planul stabilit la consultație și de capacitatea zonei donatoare, ne-am concentrat mai întâi pe construirea unei densități mai mari în față și la creștet, echilibrând totodată zona mediană pentru un rezultat uniform. Procedura a fost realizată cu protocolul Vita într-o singură ședință, cu un total de 4.500 de grefe transplantate. Zona donatoare având o densitate bună, grefele au fost distribuite conform nevoilor de acoperire planificate — densitate mai mare în zona frontală și la creștet, iar zona mediană a fost întărită pentru un aspect general mai omogen. La finalul procedurii s-a aplicat suport PRP.',
			'Danny came to our clinic from England to improve density in his frontal area and extend coverage toward the mid-scalp. Based on his consultation plan, we prioritised harvesting the maximum number of grafts and building a dense, natural-looking result in the thinning zones, aiming for good density up to the midsection. The procedure was performed with the FUE Vita technique in a single session, transplanting 5,000 grafts in total. Grafts were extracted homogeneously from the donor area with good quality, then implanted with attention to natural direction, density balance and frontal-to-mid-scalp coverage. The operation progressed normally, with PRP support applied at the end.' => 'Danny a venit la clinica noastră din Anglia pentru a-și îmbunătăți densitatea în zona frontală și a extinde acoperirea către zona mediană a scalpului. În funcție de planul stabilit la consultație, am acordat prioritate recoltării unui număr maxim de grefe și obținerii unui rezultat dens și natural în zonele rărite, urmărind o densitate bună până în zona mediană. Procedura a fost realizată cu tehnica FUE Vita într-o singură ședință, cu un total de 5.000 de grefe transplantate. Grefele au fost recoltate omogen din zona donatoare, cu o calitate bună, apoi implantate cu atenție la direcția naturală, la echilibrul densității și la acoperirea dinspre zona frontală către cea mediană. Operația a decurs normal, iar la final s-a aplicat suport PRP.',
			'Pascal came to our clinic from Canada to improve density in his frontal area and extend coverage toward the mid-scalp. Based on his consultation plan and donor capacity, we planned maximum graft extraction to cover the frontal area up to the midsection with good density, with a second session planned for full coverage. The procedure was performed with the Exosome FUE technique, transplanting 5,000 grafts in this session. Grafts were extracted homogeneously from the donor area with good hair quality, then implanted with attention to natural direction, density balance and frontal-to-mid-scalp coverage. PRP support was applied at the end of the procedure.' => 'Pascal a venit la clinica noastră din Canada pentru a-și îmbunătăți densitatea în zona frontală și a extinde acoperirea către zona mediană a scalpului. În funcție de planul stabilit la consultație și de capacitatea zonei donatoare, am planificat o recoltare maximă de grefe pentru a acoperi zona frontală până în zona mediană cu o densitate bună, urmând ca o a doua ședință să fie planificată pentru acoperirea completă. Procedura a fost realizată cu tehnica Exosome FUE, cu 5.000 de grefe transplantate în această ședință. Grefele au fost recoltate omogen din zona donatoare, cu o calitate bună a părului, apoi implantate cu atenție la direcția naturală, la echilibrul densității și la acoperirea dinspre zona frontală către cea mediană. La finalul procedurii s-a aplicat suport PRP.',
			'Ricardo came to our clinic from Ireland to restore a natural hairline and improve density across the frontal area, temples and a small thinning area on the crown. Based on his consultation plan and his wish for a natural-looking result, we adjusted the frontal line to his facial structure and planned dense implantation in the front, with additional grafts placed in the temples and crown for overall balance. The procedure was performed with the DHI Vita technique in a single session, transplanting approximately 4,200 grafts. The grafts were extracted with good hair quality, then implanted with attention to natural direction, symmetry, density balance and frontal-to-crown coverage. The operation progressed normally, with PRP support at the end.' => 'Ricardo a venit la clinica noastră din Irlanda pentru a-și reface o linie frontală naturală a părului și a îmbunătăți densitatea în zona frontală, la tâmple și într-o mică zonă rărită de la creștet. În funcție de planul stabilit la consultație și de dorința lui pentru un rezultat cu aspect natural, am adaptat linia frontală la structura feței și am planificat o implantare densă în partea din față, cu grefe suplimentare plasate la tâmple și la creștet pentru un echilibru de ansamblu. Procedura a fost realizată cu tehnica DHI Vita într-o singură ședință, cu aproximativ 4.200 de grefe transplantate. Grefele au fost recoltate cu o calitate bună a părului, apoi implantate cu atenție la direcția naturală, la simetrie, la echilibrul densității și la acoperirea dinspre zona frontală către creștet. Operația a decurs normal, iar la final s-a aplicat suport PRP.',
			'Sam came to our clinic from Ireland to improve his hairline and increase overall density across the frontal area, mid-scalp and crown. Based on his consultation plan and his wish for full coverage in a single session, we planned maximum graft extraction and focused on building good density in the frontal hairline first, then distributed the remaining grafts through the mid-scalp and crown for balanced coverage. The procedure was performed with the FUE Vita technique in a single session, transplanting 6,200 grafts in total. Grafts were extracted homogeneously from the donor area with good quality, then implanted with attention to natural direction, density balance and overall coverage. The operation progressed normally, with PRP support at the end.' => 'Sam a venit la clinica noastră din Irlanda pentru a-și îmbunătăți linia frontală a părului și a crește densitatea generală în zona frontală, în zona mediană și la creștet. În funcție de planul stabilit la consultație și de dorința lui de a obține acoperire completă într-o singură ședință, am planificat o recoltare maximă de grefe și ne-am concentrat mai întâi pe o densitate bună a liniei frontale, apoi am distribuit grefele rămase prin zona mediană și la creștet, pentru o acoperire echilibrată. Procedura a fost realizată cu tehnica FUE Vita într-o singură ședință, cu un total de 6.200 de grefe transplantate. Grefele au fost recoltate omogen din zona donatoare, cu o calitate bună, apoi implantate cu atenție la direcția naturală, la echilibrul densității și la acoperirea de ansamblu. Operația a decurs normal, iar la final s-a aplicat suport PRP.',

			// Signature-card long descriptions.
			'Our patented Exosome Treatment is derived from mesenchymal stem cells found in the umbilical cord — designed to lift hair-follicle survival to 98% over 72 hours, with faster recovery, stronger growth, and naturally lasting results.' => 'Tratamentul nostru Exosome, brevetat, este derivat din celule stem mezenchimale prezente în cordonul ombilical — conceput pentru a ridica supraviețuirea foliculilor de păr la 98% pe parcursul a 72 de ore, cu recuperare mai rapidă, creștere mai puternică și rezultate naturale, de durată.',
			'TrichoLab examines your hair and scalp with millimetric accuracy — measuring follicle density, thickness, donor capacity, and loss patterns — so every graft is planned for your unique anatomy and the result feels naturally yours.' => 'TrichoLab îți examinează părul și scalpul cu precizie milimetrică — măsurând densitatea foliculilor, grosimea firelor, capacitatea zonei donatoare și tiparele de cădere — astfel încât fiecare grefă să fie planificată pentru anatomia ta unică, iar rezultatul să pară cu adevărat al tău.',
			'Grafts lose strength the moment they leave the body. Our VITA Protocol bathes them in a specially formulated vitamin cocktail with cool-vapor application — keeping every follicle alive, nourished, and resilient until placement.' => 'Grefele își pierd din putere din clipa în care părăsesc corpul. Protocolul nostru VITA le scaldă într-un cocteil de vitamine special formulat, aplicat cu vapori reci — menținând fiecare folicul viu, hrănit și rezistent până la implantare.',
			// Floating WhatsApp button + fake WhatsApp chat popup.
			'WhatsApp chat' => 'Conversație pe WhatsApp',
			'Close chat' => 'Închide conversația',
			'online' => 'online',
			'Today' => 'Astăzi',
			'Hi! 👋 Welcome to Estecapelli. Tell us which treatment you are interested in and we will get back to you within minutes.' => 'Bună! 👋 Bine ai venit la Estecapelli. Spune-ne ce tratament te interesează și îți răspundem în câteva minute.',
			'Type a message' => 'Scrie un mesaj',
			'Write your message first' => 'Scrie mai întâi mesajul tău',
			'Send' => 'Trimite',
			'Confirm your message' => 'Confirmă mesajul',
			'This message will be sent to our WhatsApp:' => 'Acest mesaj va fi trimis pe WhatsApp-ul nostru:',
			'Cancel' => 'Anulează',
			// 404 page.
			'This page could not be found' => 'Această pagină nu a putut fi găsită',
			'The page you are looking for may have been moved or no longer exists. You can head back to the homepage, or pick one of the sections below.' => 'Pagina pe care o cauți s-ar putea să fi fost mutată sau să nu mai existe. Poți reveni la pagina principală sau poți alege una dintre secțiunile de mai jos.',
			'Back to homepage' => 'Înapoi la pagina principală',
			'Contact us' => 'Contactează-ne',
			'Popular sections' => 'Secțiuni populare',
			'Site sections' => 'Secțiunile site-ului',
		);
	}

	return $strings[ $text ] ?? $translation;
}

add_filter( 'ngettext', 'estecapelli_ro_ngettext_fallback', 25, 5 );
/** Translate pluralised template labels without changing article content. */
function estecapelli_ro_ngettext_fallback( $translation, $single, $plural, $number, $domain ) {
	if (
		'estecapelli' === $domain &&
		estecapelli_is_romanian_request() &&
		in_array( $translation, array( $single, $plural ), true )
	) {
		if ( '%d min read' === $single && '%d min read' === $plural ) {
			return '%d min de lectură';
		}
		if ( '%d star' === $single && '%d stars' === $plural ) {
			// Ratings only ever run 1–5, so the "de stele" form from 20 up
			// never applies here.
			return 1 === (int) $number ? '%d stea' : '%d stele';
		}
	}

	return $translation;
}
